//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.InsumoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="InsumoWS.InsumoWS")]
    public interface InsumoWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/InsumoWS/insertarInsumoRequest", ReplyAction="http://services.buildup.pucp.edu.pe/InsumoWS/insertarInsumoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.InsumoWS.insertarInsumoResponse insertarInsumo(BuildUp.InsumoWS.insertarInsumoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/InsumoWS/insertarInsumoRequest", ReplyAction="http://services.buildup.pucp.edu.pe/InsumoWS/insertarInsumoResponse")]
        System.Threading.Tasks.Task<BuildUp.InsumoWS.insertarInsumoResponse> insertarInsumoAsync(BuildUp.InsumoWS.insertarInsumoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/InsumoWS/eliminarInsumoRequest", ReplyAction="http://services.buildup.pucp.edu.pe/InsumoWS/eliminarInsumoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.InsumoWS.eliminarInsumoResponse eliminarInsumo(BuildUp.InsumoWS.eliminarInsumoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/InsumoWS/eliminarInsumoRequest", ReplyAction="http://services.buildup.pucp.edu.pe/InsumoWS/eliminarInsumoResponse")]
        System.Threading.Tasks.Task<BuildUp.InsumoWS.eliminarInsumoResponse> eliminarInsumoAsync(BuildUp.InsumoWS.eliminarInsumoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/InsumoWS/actualizarInsumoRequest", ReplyAction="http://services.buildup.pucp.edu.pe/InsumoWS/actualizarInsumoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.InsumoWS.actualizarInsumoResponse actualizarInsumo(BuildUp.InsumoWS.actualizarInsumoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/InsumoWS/actualizarInsumoRequest", ReplyAction="http://services.buildup.pucp.edu.pe/InsumoWS/actualizarInsumoResponse")]
        System.Threading.Tasks.Task<BuildUp.InsumoWS.actualizarInsumoResponse> actualizarInsumoAsync(BuildUp.InsumoWS.actualizarInsumoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/InsumoWS/listarInsumoRequest", ReplyAction="http://services.buildup.pucp.edu.pe/InsumoWS/listarInsumoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.InsumoWS.listarInsumoResponse listarInsumo(BuildUp.InsumoWS.listarInsumoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/InsumoWS/listarInsumoRequest", ReplyAction="http://services.buildup.pucp.edu.pe/InsumoWS/listarInsumoResponse")]
        System.Threading.Tasks.Task<BuildUp.InsumoWS.listarInsumoResponse> listarInsumoAsync(BuildUp.InsumoWS.listarInsumoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class insumo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idInsumoField;
        
        private string nombreField;
        
        private string unidadMedidaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idInsumo {
            get {
                return this.idInsumoField;
            }
            set {
                this.idInsumoField = value;
                this.RaisePropertyChanged("idInsumo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string unidadMedida {
            get {
                return this.unidadMedidaField;
            }
            set {
                this.unidadMedidaField = value;
                this.RaisePropertyChanged("unidadMedida");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarInsumo", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarInsumoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.InsumoWS.insumo insumo;
        
        public insertarInsumoRequest() {
        }
        
        public insertarInsumoRequest(BuildUp.InsumoWS.insumo insumo) {
            this.insumo = insumo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarInsumoResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarInsumoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarInsumoResponse() {
        }
        
        public insertarInsumoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarInsumo", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarInsumoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idInsumo;
        
        public eliminarInsumoRequest() {
        }
        
        public eliminarInsumoRequest(int idInsumo) {
            this.idInsumo = idInsumo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarInsumoResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarInsumoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarInsumoResponse() {
        }
        
        public eliminarInsumoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarInsumo", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarInsumoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.InsumoWS.insumo insumo;
        
        public actualizarInsumoRequest() {
        }
        
        public actualizarInsumoRequest(BuildUp.InsumoWS.insumo insumo) {
            this.insumo = insumo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarInsumoResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarInsumoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarInsumoResponse() {
        }
        
        public actualizarInsumoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInsumo", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarInsumoRequest {
        
        public listarInsumoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarInsumoResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarInsumoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.InsumoWS.insumo[] @return;
        
        public listarInsumoResponse() {
        }
        
        public listarInsumoResponse(BuildUp.InsumoWS.insumo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InsumoWSChannel : BuildUp.InsumoWS.InsumoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsumoWSClient : System.ServiceModel.ClientBase<BuildUp.InsumoWS.InsumoWS>, BuildUp.InsumoWS.InsumoWS {
        
        public InsumoWSClient() {
        }
        
        public InsumoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsumoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsumoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsumoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.InsumoWS.insertarInsumoResponse BuildUp.InsumoWS.InsumoWS.insertarInsumo(BuildUp.InsumoWS.insertarInsumoRequest request) {
            return base.Channel.insertarInsumo(request);
        }
        
        public int insertarInsumo(BuildUp.InsumoWS.insumo insumo) {
            BuildUp.InsumoWS.insertarInsumoRequest inValue = new BuildUp.InsumoWS.insertarInsumoRequest();
            inValue.insumo = insumo;
            BuildUp.InsumoWS.insertarInsumoResponse retVal = ((BuildUp.InsumoWS.InsumoWS)(this)).insertarInsumo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.InsumoWS.insertarInsumoResponse> BuildUp.InsumoWS.InsumoWS.insertarInsumoAsync(BuildUp.InsumoWS.insertarInsumoRequest request) {
            return base.Channel.insertarInsumoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.InsumoWS.insertarInsumoResponse> insertarInsumoAsync(BuildUp.InsumoWS.insumo insumo) {
            BuildUp.InsumoWS.insertarInsumoRequest inValue = new BuildUp.InsumoWS.insertarInsumoRequest();
            inValue.insumo = insumo;
            return ((BuildUp.InsumoWS.InsumoWS)(this)).insertarInsumoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.InsumoWS.eliminarInsumoResponse BuildUp.InsumoWS.InsumoWS.eliminarInsumo(BuildUp.InsumoWS.eliminarInsumoRequest request) {
            return base.Channel.eliminarInsumo(request);
        }
        
        public int eliminarInsumo(int idInsumo) {
            BuildUp.InsumoWS.eliminarInsumoRequest inValue = new BuildUp.InsumoWS.eliminarInsumoRequest();
            inValue.idInsumo = idInsumo;
            BuildUp.InsumoWS.eliminarInsumoResponse retVal = ((BuildUp.InsumoWS.InsumoWS)(this)).eliminarInsumo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.InsumoWS.eliminarInsumoResponse> BuildUp.InsumoWS.InsumoWS.eliminarInsumoAsync(BuildUp.InsumoWS.eliminarInsumoRequest request) {
            return base.Channel.eliminarInsumoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.InsumoWS.eliminarInsumoResponse> eliminarInsumoAsync(int idInsumo) {
            BuildUp.InsumoWS.eliminarInsumoRequest inValue = new BuildUp.InsumoWS.eliminarInsumoRequest();
            inValue.idInsumo = idInsumo;
            return ((BuildUp.InsumoWS.InsumoWS)(this)).eliminarInsumoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.InsumoWS.actualizarInsumoResponse BuildUp.InsumoWS.InsumoWS.actualizarInsumo(BuildUp.InsumoWS.actualizarInsumoRequest request) {
            return base.Channel.actualizarInsumo(request);
        }
        
        public int actualizarInsumo(BuildUp.InsumoWS.insumo insumo) {
            BuildUp.InsumoWS.actualizarInsumoRequest inValue = new BuildUp.InsumoWS.actualizarInsumoRequest();
            inValue.insumo = insumo;
            BuildUp.InsumoWS.actualizarInsumoResponse retVal = ((BuildUp.InsumoWS.InsumoWS)(this)).actualizarInsumo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.InsumoWS.actualizarInsumoResponse> BuildUp.InsumoWS.InsumoWS.actualizarInsumoAsync(BuildUp.InsumoWS.actualizarInsumoRequest request) {
            return base.Channel.actualizarInsumoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.InsumoWS.actualizarInsumoResponse> actualizarInsumoAsync(BuildUp.InsumoWS.insumo insumo) {
            BuildUp.InsumoWS.actualizarInsumoRequest inValue = new BuildUp.InsumoWS.actualizarInsumoRequest();
            inValue.insumo = insumo;
            return ((BuildUp.InsumoWS.InsumoWS)(this)).actualizarInsumoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.InsumoWS.listarInsumoResponse BuildUp.InsumoWS.InsumoWS.listarInsumo(BuildUp.InsumoWS.listarInsumoRequest request) {
            return base.Channel.listarInsumo(request);
        }
        
        public BuildUp.InsumoWS.insumo[] listarInsumo() {
            BuildUp.InsumoWS.listarInsumoRequest inValue = new BuildUp.InsumoWS.listarInsumoRequest();
            BuildUp.InsumoWS.listarInsumoResponse retVal = ((BuildUp.InsumoWS.InsumoWS)(this)).listarInsumo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.InsumoWS.listarInsumoResponse> BuildUp.InsumoWS.InsumoWS.listarInsumoAsync(BuildUp.InsumoWS.listarInsumoRequest request) {
            return base.Channel.listarInsumoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.InsumoWS.listarInsumoResponse> listarInsumoAsync() {
            BuildUp.InsumoWS.listarInsumoRequest inValue = new BuildUp.InsumoWS.listarInsumoRequest();
            return ((BuildUp.InsumoWS.InsumoWS)(this)).listarInsumoAsync(inValue);
        }
    }
}
