//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.TipoLadrilloWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="TipoLadrilloWS.TipoLadrilloWS")]
    public interface TipoLadrilloWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/insertarTipoLadrilloRequest", ReplyAction="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/insertarTipoLadrilloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.TipoLadrilloWS.insertarTipoLadrilloResponse insertarTipoLadrillo(BuildUp.TipoLadrilloWS.insertarTipoLadrilloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/insertarTipoLadrilloRequest", ReplyAction="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/insertarTipoLadrilloResponse")]
        System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.insertarTipoLadrilloResponse> insertarTipoLadrilloAsync(BuildUp.TipoLadrilloWS.insertarTipoLadrilloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/listarTiposLadrilloRequest", ReplyAction="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/listarTiposLadrilloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.TipoLadrilloWS.listarTiposLadrilloResponse listarTiposLadrillo(BuildUp.TipoLadrilloWS.listarTiposLadrilloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/listarTiposLadrilloRequest", ReplyAction="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/listarTiposLadrilloResponse")]
        System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.listarTiposLadrilloResponse> listarTiposLadrilloAsync(BuildUp.TipoLadrilloWS.listarTiposLadrilloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/eliminarTipoLadrilloRequest", ReplyAction="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/eliminarTipoLadrilloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.TipoLadrilloWS.eliminarTipoLadrilloResponse eliminarTipoLadrillo(BuildUp.TipoLadrilloWS.eliminarTipoLadrilloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/eliminarTipoLadrilloRequest", ReplyAction="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/eliminarTipoLadrilloResponse")]
        System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.eliminarTipoLadrilloResponse> eliminarTipoLadrilloAsync(BuildUp.TipoLadrilloWS.eliminarTipoLadrilloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/listarTipoLadrilloPorNombreReq" +
            "uest", ReplyAction="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/listarTipoLadrilloPorNombreRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreResponse listarTipoLadrilloPorNombre(BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/listarTipoLadrilloPorNombreReq" +
            "uest", ReplyAction="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/listarTipoLadrilloPorNombreRes" +
            "ponse")]
        System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreResponse> listarTipoLadrilloPorNombreAsync(BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/actualizarTipoLadrilloRequest", ReplyAction="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/actualizarTipoLadrilloResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.TipoLadrilloWS.actualizarTipoLadrilloResponse actualizarTipoLadrillo(BuildUp.TipoLadrilloWS.actualizarTipoLadrilloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/actualizarTipoLadrilloRequest", ReplyAction="http://services.buildup.pucp.edu.pe/TipoLadrilloWS/actualizarTipoLadrilloResponse" +
            "")]
        System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.actualizarTipoLadrilloResponse> actualizarTipoLadrilloAsync(BuildUp.TipoLadrilloWS.actualizarTipoLadrilloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class tipoLadrillo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double alturaField;
        
        private double anchoField;
        
        private int idTipoLadrilloField;
        
        private double largoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
                this.RaisePropertyChanged("altura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
                this.RaisePropertyChanged("ancho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTipoLadrillo {
            get {
                return this.idTipoLadrilloField;
            }
            set {
                this.idTipoLadrilloField = value;
                this.RaisePropertyChanged("idTipoLadrillo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
                this.RaisePropertyChanged("largo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoLadrillo", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoLadrilloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.TipoLadrilloWS.tipoLadrillo tipoLadrillo;
        
        public insertarTipoLadrilloRequest() {
        }
        
        public insertarTipoLadrilloRequest(BuildUp.TipoLadrilloWS.tipoLadrillo tipoLadrillo) {
            this.tipoLadrillo = tipoLadrillo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarTipoLadrilloResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarTipoLadrilloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarTipoLadrilloResponse() {
        }
        
        public insertarTipoLadrilloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTiposLadrillo", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTiposLadrilloRequest {
        
        public listarTiposLadrilloRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTiposLadrilloResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTiposLadrilloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.TipoLadrilloWS.tipoLadrillo[] @return;
        
        public listarTiposLadrilloResponse() {
        }
        
        public listarTiposLadrilloResponse(BuildUp.TipoLadrilloWS.tipoLadrillo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTipoLadrillo", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTipoLadrilloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idTipoLadrillo;
        
        public eliminarTipoLadrilloRequest() {
        }
        
        public eliminarTipoLadrilloRequest(int idTipoLadrillo) {
            this.idTipoLadrillo = idTipoLadrillo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarTipoLadrilloResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarTipoLadrilloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarTipoLadrilloResponse() {
        }
        
        public eliminarTipoLadrilloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTipoLadrilloPorNombre", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTipoLadrilloPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarTipoLadrilloPorNombreRequest() {
        }
        
        public listarTipoLadrilloPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTipoLadrilloPorNombreResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTipoLadrilloPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.TipoLadrilloWS.tipoLadrillo[] @return;
        
        public listarTipoLadrilloPorNombreResponse() {
        }
        
        public listarTipoLadrilloPorNombreResponse(BuildUp.TipoLadrilloWS.tipoLadrillo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarTipoLadrillo", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarTipoLadrilloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.TipoLadrilloWS.tipoLadrillo tipoLadrillo;
        
        public actualizarTipoLadrilloRequest() {
        }
        
        public actualizarTipoLadrilloRequest(BuildUp.TipoLadrilloWS.tipoLadrillo tipoLadrillo) {
            this.tipoLadrillo = tipoLadrillo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarTipoLadrilloResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarTipoLadrilloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarTipoLadrilloResponse() {
        }
        
        public actualizarTipoLadrilloResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoLadrilloWSChannel : BuildUp.TipoLadrilloWS.TipoLadrilloWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoLadrilloWSClient : System.ServiceModel.ClientBase<BuildUp.TipoLadrilloWS.TipoLadrilloWS>, BuildUp.TipoLadrilloWS.TipoLadrilloWS {
        
        public TipoLadrilloWSClient() {
        }
        
        public TipoLadrilloWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoLadrilloWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoLadrilloWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoLadrilloWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.TipoLadrilloWS.insertarTipoLadrilloResponse BuildUp.TipoLadrilloWS.TipoLadrilloWS.insertarTipoLadrillo(BuildUp.TipoLadrilloWS.insertarTipoLadrilloRequest request) {
            return base.Channel.insertarTipoLadrillo(request);
        }
        
        public int insertarTipoLadrillo(BuildUp.TipoLadrilloWS.tipoLadrillo tipoLadrillo) {
            BuildUp.TipoLadrilloWS.insertarTipoLadrilloRequest inValue = new BuildUp.TipoLadrilloWS.insertarTipoLadrilloRequest();
            inValue.tipoLadrillo = tipoLadrillo;
            BuildUp.TipoLadrilloWS.insertarTipoLadrilloResponse retVal = ((BuildUp.TipoLadrilloWS.TipoLadrilloWS)(this)).insertarTipoLadrillo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.insertarTipoLadrilloResponse> BuildUp.TipoLadrilloWS.TipoLadrilloWS.insertarTipoLadrilloAsync(BuildUp.TipoLadrilloWS.insertarTipoLadrilloRequest request) {
            return base.Channel.insertarTipoLadrilloAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.insertarTipoLadrilloResponse> insertarTipoLadrilloAsync(BuildUp.TipoLadrilloWS.tipoLadrillo tipoLadrillo) {
            BuildUp.TipoLadrilloWS.insertarTipoLadrilloRequest inValue = new BuildUp.TipoLadrilloWS.insertarTipoLadrilloRequest();
            inValue.tipoLadrillo = tipoLadrillo;
            return ((BuildUp.TipoLadrilloWS.TipoLadrilloWS)(this)).insertarTipoLadrilloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.TipoLadrilloWS.listarTiposLadrilloResponse BuildUp.TipoLadrilloWS.TipoLadrilloWS.listarTiposLadrillo(BuildUp.TipoLadrilloWS.listarTiposLadrilloRequest request) {
            return base.Channel.listarTiposLadrillo(request);
        }
        
        public BuildUp.TipoLadrilloWS.tipoLadrillo[] listarTiposLadrillo() {
            BuildUp.TipoLadrilloWS.listarTiposLadrilloRequest inValue = new BuildUp.TipoLadrilloWS.listarTiposLadrilloRequest();
            BuildUp.TipoLadrilloWS.listarTiposLadrilloResponse retVal = ((BuildUp.TipoLadrilloWS.TipoLadrilloWS)(this)).listarTiposLadrillo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.listarTiposLadrilloResponse> BuildUp.TipoLadrilloWS.TipoLadrilloWS.listarTiposLadrilloAsync(BuildUp.TipoLadrilloWS.listarTiposLadrilloRequest request) {
            return base.Channel.listarTiposLadrilloAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.listarTiposLadrilloResponse> listarTiposLadrilloAsync() {
            BuildUp.TipoLadrilloWS.listarTiposLadrilloRequest inValue = new BuildUp.TipoLadrilloWS.listarTiposLadrilloRequest();
            return ((BuildUp.TipoLadrilloWS.TipoLadrilloWS)(this)).listarTiposLadrilloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.TipoLadrilloWS.eliminarTipoLadrilloResponse BuildUp.TipoLadrilloWS.TipoLadrilloWS.eliminarTipoLadrillo(BuildUp.TipoLadrilloWS.eliminarTipoLadrilloRequest request) {
            return base.Channel.eliminarTipoLadrillo(request);
        }
        
        public int eliminarTipoLadrillo(int idTipoLadrillo) {
            BuildUp.TipoLadrilloWS.eliminarTipoLadrilloRequest inValue = new BuildUp.TipoLadrilloWS.eliminarTipoLadrilloRequest();
            inValue.idTipoLadrillo = idTipoLadrillo;
            BuildUp.TipoLadrilloWS.eliminarTipoLadrilloResponse retVal = ((BuildUp.TipoLadrilloWS.TipoLadrilloWS)(this)).eliminarTipoLadrillo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.eliminarTipoLadrilloResponse> BuildUp.TipoLadrilloWS.TipoLadrilloWS.eliminarTipoLadrilloAsync(BuildUp.TipoLadrilloWS.eliminarTipoLadrilloRequest request) {
            return base.Channel.eliminarTipoLadrilloAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.eliminarTipoLadrilloResponse> eliminarTipoLadrilloAsync(int idTipoLadrillo) {
            BuildUp.TipoLadrilloWS.eliminarTipoLadrilloRequest inValue = new BuildUp.TipoLadrilloWS.eliminarTipoLadrilloRequest();
            inValue.idTipoLadrillo = idTipoLadrillo;
            return ((BuildUp.TipoLadrilloWS.TipoLadrilloWS)(this)).eliminarTipoLadrilloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreResponse BuildUp.TipoLadrilloWS.TipoLadrilloWS.listarTipoLadrilloPorNombre(BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreRequest request) {
            return base.Channel.listarTipoLadrilloPorNombre(request);
        }
        
        public BuildUp.TipoLadrilloWS.tipoLadrillo[] listarTipoLadrilloPorNombre(string nombre) {
            BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreRequest inValue = new BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreRequest();
            inValue.nombre = nombre;
            BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreResponse retVal = ((BuildUp.TipoLadrilloWS.TipoLadrilloWS)(this)).listarTipoLadrilloPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreResponse> BuildUp.TipoLadrilloWS.TipoLadrilloWS.listarTipoLadrilloPorNombreAsync(BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreRequest request) {
            return base.Channel.listarTipoLadrilloPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreResponse> listarTipoLadrilloPorNombreAsync(string nombre) {
            BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreRequest inValue = new BuildUp.TipoLadrilloWS.listarTipoLadrilloPorNombreRequest();
            inValue.nombre = nombre;
            return ((BuildUp.TipoLadrilloWS.TipoLadrilloWS)(this)).listarTipoLadrilloPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.TipoLadrilloWS.actualizarTipoLadrilloResponse BuildUp.TipoLadrilloWS.TipoLadrilloWS.actualizarTipoLadrillo(BuildUp.TipoLadrilloWS.actualizarTipoLadrilloRequest request) {
            return base.Channel.actualizarTipoLadrillo(request);
        }
        
        public int actualizarTipoLadrillo(BuildUp.TipoLadrilloWS.tipoLadrillo tipoLadrillo) {
            BuildUp.TipoLadrilloWS.actualizarTipoLadrilloRequest inValue = new BuildUp.TipoLadrilloWS.actualizarTipoLadrilloRequest();
            inValue.tipoLadrillo = tipoLadrillo;
            BuildUp.TipoLadrilloWS.actualizarTipoLadrilloResponse retVal = ((BuildUp.TipoLadrilloWS.TipoLadrilloWS)(this)).actualizarTipoLadrillo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.actualizarTipoLadrilloResponse> BuildUp.TipoLadrilloWS.TipoLadrilloWS.actualizarTipoLadrilloAsync(BuildUp.TipoLadrilloWS.actualizarTipoLadrilloRequest request) {
            return base.Channel.actualizarTipoLadrilloAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.TipoLadrilloWS.actualizarTipoLadrilloResponse> actualizarTipoLadrilloAsync(BuildUp.TipoLadrilloWS.tipoLadrillo tipoLadrillo) {
            BuildUp.TipoLadrilloWS.actualizarTipoLadrilloRequest inValue = new BuildUp.TipoLadrilloWS.actualizarTipoLadrilloRequest();
            inValue.tipoLadrillo = tipoLadrillo;
            return ((BuildUp.TipoLadrilloWS.TipoLadrilloWS)(this)).actualizarTipoLadrilloAsync(inValue);
        }
    }
}
