//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.OSalidaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="OSalidaWS.OrdenSalidaWS")]
    public interface OrdenSalidaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/insertarRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/insertarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OSalidaWS.insertarResponse insertar(BuildUp.OSalidaWS.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/insertarRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/insertarResponse")]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.insertarResponse> insertarAsync(BuildUp.OSalidaWS.insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/actualizarRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/actualizarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OSalidaWS.actualizarResponse actualizar(BuildUp.OSalidaWS.actualizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/actualizarRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/actualizarResponse")]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.actualizarResponse> actualizarAsync(BuildUp.OSalidaWS.actualizarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/eliminarRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/eliminarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OSalidaWS.eliminarResponse eliminar(BuildUp.OSalidaWS.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/eliminarRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/eliminarResponse")]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.eliminarResponse> eliminarAsync(BuildUp.OSalidaWS.eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OSalidaWS.listarOrdenesSalidaResponse listarOrdenesSalida(BuildUp.OSalidaWS.listarOrdenesSalidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaResponse")]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaResponse> listarOrdenesSalidaAsync(BuildUp.OSalidaWS.listarOrdenesSalidaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaConParametro" +
            "sRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaConParametro" +
            "sResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse listarOrdenesSalidaConParametros(BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaConParametro" +
            "sRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaConParametro" +
            "sResponse")]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse> listarOrdenesSalidaConParametrosAsync(BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class ordenSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idOrdenSalidaField;
        
        private lineaOrdenSalida[] lineasOrdenSalidaField;
        
        private operario operarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idOrdenSalida {
            get {
                return this.idOrdenSalidaField;
            }
            set {
                this.idOrdenSalidaField = value;
                this.RaisePropertyChanged("idOrdenSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineasOrdenSalida", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public lineaOrdenSalida[] lineasOrdenSalida {
            get {
                return this.lineasOrdenSalidaField;
            }
            set {
                this.lineasOrdenSalidaField = value;
                this.RaisePropertyChanged("lineasOrdenSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public operario operario {
            get {
                return this.operarioField;
            }
            set {
                this.operarioField = value;
                this.RaisePropertyChanged("operario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class lineaOrdenSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private int idLineaOrdenSalidaField;
        
        private ordenSalida ordenSalidaField;
        
        private tipoLadrillo tipoLadrilloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLineaOrdenSalida {
            get {
                return this.idLineaOrdenSalidaField;
            }
            set {
                this.idLineaOrdenSalidaField = value;
                this.RaisePropertyChanged("idLineaOrdenSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ordenSalida ordenSalida {
            get {
                return this.ordenSalidaField;
            }
            set {
                this.ordenSalidaField = value;
                this.RaisePropertyChanged("ordenSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tipoLadrillo tipoLadrillo {
            get {
                return this.tipoLadrilloField;
            }
            set {
                this.tipoLadrilloField = value;
                this.RaisePropertyChanged("tipoLadrillo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class tipoLadrillo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double alturaField;
        
        private double anchoField;
        
        private int idTipoLadrilloField;
        
        private double largoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
                this.RaisePropertyChanged("altura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
                this.RaisePropertyChanged("ancho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTipoLadrillo {
            get {
                return this.idTipoLadrilloField;
            }
            set {
                this.idTipoLadrilloField = value;
                this.RaisePropertyChanged("idTipoLadrillo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
                this.RaisePropertyChanged("largo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class lineaProduccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idLineaProduccionField;
        
        private string nombreField;
        
        private operario[] operariosField;
        
        private supervisor[] supervisoresField;
        
        private tipoLadrillo tipoLadrilloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLineaProduccion {
            get {
                return this.idLineaProduccionField;
            }
            set {
                this.idLineaProduccionField = value;
                this.RaisePropertyChanged("idLineaProduccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("operarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public operario[] operarios {
            get {
                return this.operariosField;
            }
            set {
                this.operariosField = value;
                this.RaisePropertyChanged("operarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supervisores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public supervisor[] supervisores {
            get {
                return this.supervisoresField;
            }
            set {
                this.supervisoresField = value;
                this.RaisePropertyChanged("supervisores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoLadrillo tipoLadrillo {
            get {
                return this.tipoLadrilloField;
            }
            set {
                this.tipoLadrilloField = value;
                this.RaisePropertyChanged("tipoLadrillo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class operario : persona {
        
        private lineaProduccion lineaProduccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(supervisor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(operario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidosField;
        
        private string correoField;
        
        private System.DateTime fechaFinContratoField;
        
        private bool fechaFinContratoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonaField;
        
        private string nombresField;
        
        private string rolField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFinContrato {
            get {
                return this.fechaFinContratoField;
            }
            set {
                this.fechaFinContratoField = value;
                this.RaisePropertyChanged("fechaFinContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinContratoSpecified {
            get {
                return this.fechaFinContratoFieldSpecified;
            }
            set {
                this.fechaFinContratoFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinContratoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class supervisor : persona {
        
        private lineaProduccion lineaProduccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.OSalidaWS.ordenSalida ordenSalida;
        
        public insertarRequest() {
        }
        
        public insertarRequest(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            this.ordenSalida = ordenSalida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizar", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.OSalidaWS.ordenSalida ordenSalida;
        
        public actualizarRequest() {
        }
        
        public actualizarRequest(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            this.ordenSalida = ordenSalida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarResponse() {
        }
        
        public actualizarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOrdenSalida;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(int idOrdenSalida) {
            this.idOrdenSalida = idOrdenSalida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesSalida", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesSalidaRequest {
        
        public listarOrdenesSalidaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesSalidaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesSalidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.OSalidaWS.ordenSalida[] @return;
        
        public listarOrdenesSalidaResponse() {
        }
        
        public listarOrdenesSalidaResponse(BuildUp.OSalidaWS.ordenSalida[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesSalidaConParametros", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesSalidaConParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreOperario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fechaRegistro;
        
        public listarOrdenesSalidaConParametrosRequest() {
        }
        
        public listarOrdenesSalidaConParametrosRequest(string nombreOperario, System.DateTime fechaRegistro) {
            this.nombreOperario = nombreOperario;
            this.fechaRegistro = fechaRegistro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesSalidaConParametrosResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesSalidaConParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.OSalidaWS.ordenSalida[] @return;
        
        public listarOrdenesSalidaConParametrosResponse() {
        }
        
        public listarOrdenesSalidaConParametrosResponse(BuildUp.OSalidaWS.ordenSalida[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenSalidaWSChannel : BuildUp.OSalidaWS.OrdenSalidaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenSalidaWSClient : System.ServiceModel.ClientBase<BuildUp.OSalidaWS.OrdenSalidaWS>, BuildUp.OSalidaWS.OrdenSalidaWS {
        
        public OrdenSalidaWSClient() {
        }
        
        public OrdenSalidaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenSalidaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenSalidaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenSalidaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OSalidaWS.insertarResponse BuildUp.OSalidaWS.OrdenSalidaWS.insertar(BuildUp.OSalidaWS.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            BuildUp.OSalidaWS.insertarRequest inValue = new BuildUp.OSalidaWS.insertarRequest();
            inValue.ordenSalida = ordenSalida;
            BuildUp.OSalidaWS.insertarResponse retVal = ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.insertarResponse> BuildUp.OSalidaWS.OrdenSalidaWS.insertarAsync(BuildUp.OSalidaWS.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OSalidaWS.insertarResponse> insertarAsync(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            BuildUp.OSalidaWS.insertarRequest inValue = new BuildUp.OSalidaWS.insertarRequest();
            inValue.ordenSalida = ordenSalida;
            return ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OSalidaWS.actualizarResponse BuildUp.OSalidaWS.OrdenSalidaWS.actualizar(BuildUp.OSalidaWS.actualizarRequest request) {
            return base.Channel.actualizar(request);
        }
        
        public int actualizar(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            BuildUp.OSalidaWS.actualizarRequest inValue = new BuildUp.OSalidaWS.actualizarRequest();
            inValue.ordenSalida = ordenSalida;
            BuildUp.OSalidaWS.actualizarResponse retVal = ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).actualizar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.actualizarResponse> BuildUp.OSalidaWS.OrdenSalidaWS.actualizarAsync(BuildUp.OSalidaWS.actualizarRequest request) {
            return base.Channel.actualizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OSalidaWS.actualizarResponse> actualizarAsync(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            BuildUp.OSalidaWS.actualizarRequest inValue = new BuildUp.OSalidaWS.actualizarRequest();
            inValue.ordenSalida = ordenSalida;
            return ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).actualizarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OSalidaWS.eliminarResponse BuildUp.OSalidaWS.OrdenSalidaWS.eliminar(BuildUp.OSalidaWS.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(int idOrdenSalida) {
            BuildUp.OSalidaWS.eliminarRequest inValue = new BuildUp.OSalidaWS.eliminarRequest();
            inValue.idOrdenSalida = idOrdenSalida;
            BuildUp.OSalidaWS.eliminarResponse retVal = ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.eliminarResponse> BuildUp.OSalidaWS.OrdenSalidaWS.eliminarAsync(BuildUp.OSalidaWS.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OSalidaWS.eliminarResponse> eliminarAsync(int idOrdenSalida) {
            BuildUp.OSalidaWS.eliminarRequest inValue = new BuildUp.OSalidaWS.eliminarRequest();
            inValue.idOrdenSalida = idOrdenSalida;
            return ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OSalidaWS.listarOrdenesSalidaResponse BuildUp.OSalidaWS.OrdenSalidaWS.listarOrdenesSalida(BuildUp.OSalidaWS.listarOrdenesSalidaRequest request) {
            return base.Channel.listarOrdenesSalida(request);
        }
        
        public BuildUp.OSalidaWS.ordenSalida[] listarOrdenesSalida() {
            BuildUp.OSalidaWS.listarOrdenesSalidaRequest inValue = new BuildUp.OSalidaWS.listarOrdenesSalidaRequest();
            BuildUp.OSalidaWS.listarOrdenesSalidaResponse retVal = ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).listarOrdenesSalida(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaResponse> BuildUp.OSalidaWS.OrdenSalidaWS.listarOrdenesSalidaAsync(BuildUp.OSalidaWS.listarOrdenesSalidaRequest request) {
            return base.Channel.listarOrdenesSalidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaResponse> listarOrdenesSalidaAsync() {
            BuildUp.OSalidaWS.listarOrdenesSalidaRequest inValue = new BuildUp.OSalidaWS.listarOrdenesSalidaRequest();
            return ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).listarOrdenesSalidaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse BuildUp.OSalidaWS.OrdenSalidaWS.listarOrdenesSalidaConParametros(BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest request) {
            return base.Channel.listarOrdenesSalidaConParametros(request);
        }
        
        public BuildUp.OSalidaWS.ordenSalida[] listarOrdenesSalidaConParametros(string nombreOperario, System.DateTime fechaRegistro) {
            BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest inValue = new BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest();
            inValue.nombreOperario = nombreOperario;
            inValue.fechaRegistro = fechaRegistro;
            BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse retVal = ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).listarOrdenesSalidaConParametros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse> BuildUp.OSalidaWS.OrdenSalidaWS.listarOrdenesSalidaConParametrosAsync(BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest request) {
            return base.Channel.listarOrdenesSalidaConParametrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse> listarOrdenesSalidaConParametrosAsync(string nombreOperario, System.DateTime fechaRegistro) {
            BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest inValue = new BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest();
            inValue.nombreOperario = nombreOperario;
            inValue.fechaRegistro = fechaRegistro;
            return ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).listarOrdenesSalidaConParametrosAsync(inValue);
        }
    }
}
