//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.OSalidaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="OSalidaWS.OrdenSalidaWS")]
    public interface OrdenSalidaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/insertarOrdenSalidaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/insertarOrdenSalidaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OSalidaWS.insertarOrdenSalidaResponse insertarOrdenSalida(BuildUp.OSalidaWS.insertarOrdenSalidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/insertarOrdenSalidaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/insertarOrdenSalidaResponse")]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.insertarOrdenSalidaResponse> insertarOrdenSalidaAsync(BuildUp.OSalidaWS.insertarOrdenSalidaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/actualizarOrdenSalidaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/actualizarOrdenSalidaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OSalidaWS.actualizarOrdenSalidaResponse actualizarOrdenSalida(BuildUp.OSalidaWS.actualizarOrdenSalidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/actualizarOrdenSalidaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/actualizarOrdenSalidaResponse")]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.actualizarOrdenSalidaResponse> actualizarOrdenSalidaAsync(BuildUp.OSalidaWS.actualizarOrdenSalidaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/eliminarOrdenSalidaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/eliminarOrdenSalidaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OSalidaWS.eliminarOrdenSalidaResponse eliminarOrdenSalida(BuildUp.OSalidaWS.eliminarOrdenSalidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/eliminarOrdenSalidaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/eliminarOrdenSalidaResponse")]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.eliminarOrdenSalidaResponse> eliminarOrdenSalidaAsync(BuildUp.OSalidaWS.eliminarOrdenSalidaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OSalidaWS.listarOrdenesSalidaResponse listarOrdenesSalida(BuildUp.OSalidaWS.listarOrdenesSalidaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaResponse")]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaResponse> listarOrdenesSalidaAsync(BuildUp.OSalidaWS.listarOrdenesSalidaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaConParametro" +
            "sRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaConParametro" +
            "sResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse listarOrdenesSalidaConParametros(BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaConParametro" +
            "sRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OrdenSalidaWS/listarOrdenesSalidaConParametro" +
            "sResponse")]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse> listarOrdenesSalidaConParametrosAsync(BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class ordenSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idOrdenSalidaField;
        
        private lineaOrdenSalida[] lineasOrdenSalidaField;
        
        private operario operarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idOrdenSalida {
            get {
                return this.idOrdenSalidaField;
            }
            set {
                this.idOrdenSalidaField = value;
                this.RaisePropertyChanged("idOrdenSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lineasOrdenSalida", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public lineaOrdenSalida[] lineasOrdenSalida {
            get {
                return this.lineasOrdenSalidaField;
            }
            set {
                this.lineasOrdenSalidaField = value;
                this.RaisePropertyChanged("lineasOrdenSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public operario operario {
            get {
                return this.operarioField;
            }
            set {
                this.operarioField = value;
                this.RaisePropertyChanged("operario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class lineaOrdenSalida : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadField;
        
        private int idLineaOrdenSalidaField;
        
        private ordenSalida ordenSalidaField;
        
        private tipoLadrillo tipoLadrilloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLineaOrdenSalida {
            get {
                return this.idLineaOrdenSalidaField;
            }
            set {
                this.idLineaOrdenSalidaField = value;
                this.RaisePropertyChanged("idLineaOrdenSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public ordenSalida ordenSalida {
            get {
                return this.ordenSalidaField;
            }
            set {
                this.ordenSalidaField = value;
                this.RaisePropertyChanged("ordenSalida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public tipoLadrillo tipoLadrillo {
            get {
                return this.tipoLadrilloField;
            }
            set {
                this.tipoLadrilloField = value;
                this.RaisePropertyChanged("tipoLadrillo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class tipoLadrillo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double alturaField;
        
        private double anchoField;
        
        private int idTipoLadrilloField;
        
        private double largoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
                this.RaisePropertyChanged("altura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
                this.RaisePropertyChanged("ancho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTipoLadrillo {
            get {
                return this.idTipoLadrilloField;
            }
            set {
                this.idTipoLadrilloField = value;
                this.RaisePropertyChanged("idTipoLadrillo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
                this.RaisePropertyChanged("largo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class lineaProduccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idLineaProduccionField;
        
        private string nombreField;
        
        private operario[] operariosField;
        
        private supervisor[] supervisoresField;
        
        private tipoLadrillo tipoLadrilloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLineaProduccion {
            get {
                return this.idLineaProduccionField;
            }
            set {
                this.idLineaProduccionField = value;
                this.RaisePropertyChanged("idLineaProduccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("operarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public operario[] operarios {
            get {
                return this.operariosField;
            }
            set {
                this.operariosField = value;
                this.RaisePropertyChanged("operarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supervisores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public supervisor[] supervisores {
            get {
                return this.supervisoresField;
            }
            set {
                this.supervisoresField = value;
                this.RaisePropertyChanged("supervisores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoLadrillo tipoLadrillo {
            get {
                return this.tipoLadrilloField;
            }
            set {
                this.tipoLadrilloField = value;
                this.RaisePropertyChanged("tipoLadrillo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class operario : persona {
        
        private lineaProduccion lineaProduccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(supervisor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(operario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidosField;
        
        private string correoField;
        
        private System.DateTime fechaFinContratoField;
        
        private bool fechaFinContratoFieldSpecified;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonaField;
        
        private string nombresField;
        
        private string rolField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFinContrato {
            get {
                return this.fechaFinContratoField;
            }
            set {
                this.fechaFinContratoField = value;
                this.RaisePropertyChanged("fechaFinContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinContratoSpecified {
            get {
                return this.fechaFinContratoFieldSpecified;
            }
            set {
                this.fechaFinContratoFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinContratoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class supervisor : persona {
        
        private lineaProduccion lineaProduccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenSalida", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOrdenSalidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.OSalidaWS.ordenSalida ordenSalida;
        
        public insertarOrdenSalidaRequest() {
        }
        
        public insertarOrdenSalidaRequest(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            this.ordenSalida = ordenSalida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOrdenSalidaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOrdenSalidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarOrdenSalidaResponse() {
        }
        
        public insertarOrdenSalidaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarOrdenSalida", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarOrdenSalidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.OSalidaWS.ordenSalida ordenSalida;
        
        public actualizarOrdenSalidaRequest() {
        }
        
        public actualizarOrdenSalidaRequest(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            this.ordenSalida = ordenSalida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarOrdenSalidaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarOrdenSalidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarOrdenSalidaResponse() {
        }
        
        public actualizarOrdenSalidaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenSalida", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOrdenSalidaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOrdenSalida;
        
        public eliminarOrdenSalidaRequest() {
        }
        
        public eliminarOrdenSalidaRequest(int idOrdenSalida) {
            this.idOrdenSalida = idOrdenSalida;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOrdenSalidaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOrdenSalidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarOrdenSalidaResponse() {
        }
        
        public eliminarOrdenSalidaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesSalida", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesSalidaRequest {
        
        public listarOrdenesSalidaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesSalidaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesSalidaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.OSalidaWS.ordenSalida[] @return;
        
        public listarOrdenesSalidaResponse() {
        }
        
        public listarOrdenesSalidaResponse(BuildUp.OSalidaWS.ordenSalida[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesSalidaConParametros", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesSalidaConParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreOperario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_inf;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime fecha_sup;
        
        public listarOrdenesSalidaConParametrosRequest() {
        }
        
        public listarOrdenesSalidaConParametrosRequest(string nombreOperario, System.DateTime fecha_inf, System.DateTime fecha_sup) {
            this.nombreOperario = nombreOperario;
            this.fecha_inf = fecha_inf;
            this.fecha_sup = fecha_sup;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOrdenesSalidaConParametrosResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOrdenesSalidaConParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.OSalidaWS.ordenSalida[] @return;
        
        public listarOrdenesSalidaConParametrosResponse() {
        }
        
        public listarOrdenesSalidaConParametrosResponse(BuildUp.OSalidaWS.ordenSalida[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrdenSalidaWSChannel : BuildUp.OSalidaWS.OrdenSalidaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrdenSalidaWSClient : System.ServiceModel.ClientBase<BuildUp.OSalidaWS.OrdenSalidaWS>, BuildUp.OSalidaWS.OrdenSalidaWS {
        
        public OrdenSalidaWSClient() {
        }
        
        public OrdenSalidaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrdenSalidaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenSalidaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrdenSalidaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OSalidaWS.insertarOrdenSalidaResponse BuildUp.OSalidaWS.OrdenSalidaWS.insertarOrdenSalida(BuildUp.OSalidaWS.insertarOrdenSalidaRequest request) {
            return base.Channel.insertarOrdenSalida(request);
        }
        
        public int insertarOrdenSalida(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            BuildUp.OSalidaWS.insertarOrdenSalidaRequest inValue = new BuildUp.OSalidaWS.insertarOrdenSalidaRequest();
            inValue.ordenSalida = ordenSalida;
            BuildUp.OSalidaWS.insertarOrdenSalidaResponse retVal = ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).insertarOrdenSalida(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.insertarOrdenSalidaResponse> BuildUp.OSalidaWS.OrdenSalidaWS.insertarOrdenSalidaAsync(BuildUp.OSalidaWS.insertarOrdenSalidaRequest request) {
            return base.Channel.insertarOrdenSalidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OSalidaWS.insertarOrdenSalidaResponse> insertarOrdenSalidaAsync(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            BuildUp.OSalidaWS.insertarOrdenSalidaRequest inValue = new BuildUp.OSalidaWS.insertarOrdenSalidaRequest();
            inValue.ordenSalida = ordenSalida;
            return ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).insertarOrdenSalidaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OSalidaWS.actualizarOrdenSalidaResponse BuildUp.OSalidaWS.OrdenSalidaWS.actualizarOrdenSalida(BuildUp.OSalidaWS.actualizarOrdenSalidaRequest request) {
            return base.Channel.actualizarOrdenSalida(request);
        }
        
        public int actualizarOrdenSalida(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            BuildUp.OSalidaWS.actualizarOrdenSalidaRequest inValue = new BuildUp.OSalidaWS.actualizarOrdenSalidaRequest();
            inValue.ordenSalida = ordenSalida;
            BuildUp.OSalidaWS.actualizarOrdenSalidaResponse retVal = ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).actualizarOrdenSalida(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.actualizarOrdenSalidaResponse> BuildUp.OSalidaWS.OrdenSalidaWS.actualizarOrdenSalidaAsync(BuildUp.OSalidaWS.actualizarOrdenSalidaRequest request) {
            return base.Channel.actualizarOrdenSalidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OSalidaWS.actualizarOrdenSalidaResponse> actualizarOrdenSalidaAsync(BuildUp.OSalidaWS.ordenSalida ordenSalida) {
            BuildUp.OSalidaWS.actualizarOrdenSalidaRequest inValue = new BuildUp.OSalidaWS.actualizarOrdenSalidaRequest();
            inValue.ordenSalida = ordenSalida;
            return ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).actualizarOrdenSalidaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OSalidaWS.eliminarOrdenSalidaResponse BuildUp.OSalidaWS.OrdenSalidaWS.eliminarOrdenSalida(BuildUp.OSalidaWS.eliminarOrdenSalidaRequest request) {
            return base.Channel.eliminarOrdenSalida(request);
        }
        
        public int eliminarOrdenSalida(int idOrdenSalida) {
            BuildUp.OSalidaWS.eliminarOrdenSalidaRequest inValue = new BuildUp.OSalidaWS.eliminarOrdenSalidaRequest();
            inValue.idOrdenSalida = idOrdenSalida;
            BuildUp.OSalidaWS.eliminarOrdenSalidaResponse retVal = ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).eliminarOrdenSalida(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.eliminarOrdenSalidaResponse> BuildUp.OSalidaWS.OrdenSalidaWS.eliminarOrdenSalidaAsync(BuildUp.OSalidaWS.eliminarOrdenSalidaRequest request) {
            return base.Channel.eliminarOrdenSalidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OSalidaWS.eliminarOrdenSalidaResponse> eliminarOrdenSalidaAsync(int idOrdenSalida) {
            BuildUp.OSalidaWS.eliminarOrdenSalidaRequest inValue = new BuildUp.OSalidaWS.eliminarOrdenSalidaRequest();
            inValue.idOrdenSalida = idOrdenSalida;
            return ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).eliminarOrdenSalidaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OSalidaWS.listarOrdenesSalidaResponse BuildUp.OSalidaWS.OrdenSalidaWS.listarOrdenesSalida(BuildUp.OSalidaWS.listarOrdenesSalidaRequest request) {
            return base.Channel.listarOrdenesSalida(request);
        }
        
        public BuildUp.OSalidaWS.ordenSalida[] listarOrdenesSalida() {
            BuildUp.OSalidaWS.listarOrdenesSalidaRequest inValue = new BuildUp.OSalidaWS.listarOrdenesSalidaRequest();
            BuildUp.OSalidaWS.listarOrdenesSalidaResponse retVal = ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).listarOrdenesSalida(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaResponse> BuildUp.OSalidaWS.OrdenSalidaWS.listarOrdenesSalidaAsync(BuildUp.OSalidaWS.listarOrdenesSalidaRequest request) {
            return base.Channel.listarOrdenesSalidaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaResponse> listarOrdenesSalidaAsync() {
            BuildUp.OSalidaWS.listarOrdenesSalidaRequest inValue = new BuildUp.OSalidaWS.listarOrdenesSalidaRequest();
            return ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).listarOrdenesSalidaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse BuildUp.OSalidaWS.OrdenSalidaWS.listarOrdenesSalidaConParametros(BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest request) {
            return base.Channel.listarOrdenesSalidaConParametros(request);
        }
        
        public BuildUp.OSalidaWS.ordenSalida[] listarOrdenesSalidaConParametros(string nombreOperario, System.DateTime fecha_inf, System.DateTime fecha_sup) {
            BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest inValue = new BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest();
            inValue.nombreOperario = nombreOperario;
            inValue.fecha_inf = fecha_inf;
            inValue.fecha_sup = fecha_sup;
            BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse retVal = ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).listarOrdenesSalidaConParametros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse> BuildUp.OSalidaWS.OrdenSalidaWS.listarOrdenesSalidaConParametrosAsync(BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest request) {
            return base.Channel.listarOrdenesSalidaConParametrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosResponse> listarOrdenesSalidaConParametrosAsync(string nombreOperario, System.DateTime fecha_inf, System.DateTime fecha_sup) {
            BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest inValue = new BuildUp.OSalidaWS.listarOrdenesSalidaConParametrosRequest();
            inValue.nombreOperario = nombreOperario;
            inValue.fecha_inf = fecha_inf;
            inValue.fecha_sup = fecha_sup;
            return ((BuildUp.OSalidaWS.OrdenSalidaWS)(this)).listarOrdenesSalidaConParametrosAsync(inValue);
        }
    }
}
