//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.RespuestaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="RespuestaWS.RespuestaWS")]
    public interface RespuestaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RespuestaWS/eliminarRespuestaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RespuestaWS/eliminarRespuestaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.RespuestaWS.eliminarRespuestaResponse eliminarRespuesta(BuildUp.RespuestaWS.eliminarRespuestaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RespuestaWS/eliminarRespuestaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RespuestaWS/eliminarRespuestaResponse")]
        System.Threading.Tasks.Task<BuildUp.RespuestaWS.eliminarRespuestaResponse> eliminarRespuestaAsync(BuildUp.RespuestaWS.eliminarRespuestaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RespuestaWS/actualizarRespuestaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RespuestaWS/actualizarRespuestaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.RespuestaWS.actualizarRespuestaResponse actualizarRespuesta(BuildUp.RespuestaWS.actualizarRespuestaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RespuestaWS/actualizarRespuestaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RespuestaWS/actualizarRespuestaResponse")]
        System.Threading.Tasks.Task<BuildUp.RespuestaWS.actualizarRespuestaResponse> actualizarRespuestaAsync(BuildUp.RespuestaWS.actualizarRespuestaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RespuestaWS/insertarRespuestaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RespuestaWS/insertarRespuestaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.RespuestaWS.insertarRespuestaResponse insertarRespuesta(BuildUp.RespuestaWS.insertarRespuestaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RespuestaWS/insertarRespuestaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RespuestaWS/insertarRespuestaResponse")]
        System.Threading.Tasks.Task<BuildUp.RespuestaWS.insertarRespuestaResponse> insertarRespuestaAsync(BuildUp.RespuestaWS.insertarRespuestaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RespuestaWS/listarRespuestaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RespuestaWS/listarRespuestaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.RespuestaWS.listarRespuestaResponse listarRespuesta(BuildUp.RespuestaWS.listarRespuestaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RespuestaWS/listarRespuestaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RespuestaWS/listarRespuestaResponse")]
        System.Threading.Tasks.Task<BuildUp.RespuestaWS.listarRespuestaResponse> listarRespuestaAsync(BuildUp.RespuestaWS.listarRespuestaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRespuesta", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRespuestaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idRespuesta;
        
        public eliminarRespuestaRequest() {
        }
        
        public eliminarRespuestaRequest(int idRespuesta) {
            this.idRespuesta = idRespuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRespuestaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRespuestaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarRespuestaResponse() {
        }
        
        public eliminarRespuestaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idRespuestaField;
        
        private string tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idRespuesta {
            get {
                return this.idRespuestaField;
            }
            set {
                this.idRespuestaField = value;
                this.RaisePropertyChanged("idRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarRespuesta", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarRespuestaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.RespuestaWS.respuesta respuesta;
        
        public actualizarRespuestaRequest() {
        }
        
        public actualizarRespuestaRequest(BuildUp.RespuestaWS.respuesta respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarRespuestaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarRespuestaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarRespuestaResponse() {
        }
        
        public actualizarRespuestaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRespuesta", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRespuestaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.RespuestaWS.respuesta respuesta;
        
        public insertarRespuestaRequest() {
        }
        
        public insertarRespuestaRequest(BuildUp.RespuestaWS.respuesta respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRespuestaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRespuestaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarRespuestaResponse() {
        }
        
        public insertarRespuestaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarRespuesta", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRespuestaRequest {
        
        public listarRespuestaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarRespuestaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRespuestaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.RespuestaWS.respuesta[] @return;
        
        public listarRespuestaResponse() {
        }
        
        public listarRespuestaResponse(BuildUp.RespuestaWS.respuesta[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RespuestaWSChannel : BuildUp.RespuestaWS.RespuestaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RespuestaWSClient : System.ServiceModel.ClientBase<BuildUp.RespuestaWS.RespuestaWS>, BuildUp.RespuestaWS.RespuestaWS {
        
        public RespuestaWSClient() {
        }
        
        public RespuestaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RespuestaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RespuestaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RespuestaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.RespuestaWS.eliminarRespuestaResponse BuildUp.RespuestaWS.RespuestaWS.eliminarRespuesta(BuildUp.RespuestaWS.eliminarRespuestaRequest request) {
            return base.Channel.eliminarRespuesta(request);
        }
        
        public int eliminarRespuesta(int idRespuesta) {
            BuildUp.RespuestaWS.eliminarRespuestaRequest inValue = new BuildUp.RespuestaWS.eliminarRespuestaRequest();
            inValue.idRespuesta = idRespuesta;
            BuildUp.RespuestaWS.eliminarRespuestaResponse retVal = ((BuildUp.RespuestaWS.RespuestaWS)(this)).eliminarRespuesta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.RespuestaWS.eliminarRespuestaResponse> BuildUp.RespuestaWS.RespuestaWS.eliminarRespuestaAsync(BuildUp.RespuestaWS.eliminarRespuestaRequest request) {
            return base.Channel.eliminarRespuestaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.RespuestaWS.eliminarRespuestaResponse> eliminarRespuestaAsync(int idRespuesta) {
            BuildUp.RespuestaWS.eliminarRespuestaRequest inValue = new BuildUp.RespuestaWS.eliminarRespuestaRequest();
            inValue.idRespuesta = idRespuesta;
            return ((BuildUp.RespuestaWS.RespuestaWS)(this)).eliminarRespuestaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.RespuestaWS.actualizarRespuestaResponse BuildUp.RespuestaWS.RespuestaWS.actualizarRespuesta(BuildUp.RespuestaWS.actualizarRespuestaRequest request) {
            return base.Channel.actualizarRespuesta(request);
        }
        
        public int actualizarRespuesta(BuildUp.RespuestaWS.respuesta respuesta) {
            BuildUp.RespuestaWS.actualizarRespuestaRequest inValue = new BuildUp.RespuestaWS.actualizarRespuestaRequest();
            inValue.respuesta = respuesta;
            BuildUp.RespuestaWS.actualizarRespuestaResponse retVal = ((BuildUp.RespuestaWS.RespuestaWS)(this)).actualizarRespuesta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.RespuestaWS.actualizarRespuestaResponse> BuildUp.RespuestaWS.RespuestaWS.actualizarRespuestaAsync(BuildUp.RespuestaWS.actualizarRespuestaRequest request) {
            return base.Channel.actualizarRespuestaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.RespuestaWS.actualizarRespuestaResponse> actualizarRespuestaAsync(BuildUp.RespuestaWS.respuesta respuesta) {
            BuildUp.RespuestaWS.actualizarRespuestaRequest inValue = new BuildUp.RespuestaWS.actualizarRespuestaRequest();
            inValue.respuesta = respuesta;
            return ((BuildUp.RespuestaWS.RespuestaWS)(this)).actualizarRespuestaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.RespuestaWS.insertarRespuestaResponse BuildUp.RespuestaWS.RespuestaWS.insertarRespuesta(BuildUp.RespuestaWS.insertarRespuestaRequest request) {
            return base.Channel.insertarRespuesta(request);
        }
        
        public int insertarRespuesta(BuildUp.RespuestaWS.respuesta respuesta) {
            BuildUp.RespuestaWS.insertarRespuestaRequest inValue = new BuildUp.RespuestaWS.insertarRespuestaRequest();
            inValue.respuesta = respuesta;
            BuildUp.RespuestaWS.insertarRespuestaResponse retVal = ((BuildUp.RespuestaWS.RespuestaWS)(this)).insertarRespuesta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.RespuestaWS.insertarRespuestaResponse> BuildUp.RespuestaWS.RespuestaWS.insertarRespuestaAsync(BuildUp.RespuestaWS.insertarRespuestaRequest request) {
            return base.Channel.insertarRespuestaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.RespuestaWS.insertarRespuestaResponse> insertarRespuestaAsync(BuildUp.RespuestaWS.respuesta respuesta) {
            BuildUp.RespuestaWS.insertarRespuestaRequest inValue = new BuildUp.RespuestaWS.insertarRespuestaRequest();
            inValue.respuesta = respuesta;
            return ((BuildUp.RespuestaWS.RespuestaWS)(this)).insertarRespuestaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.RespuestaWS.listarRespuestaResponse BuildUp.RespuestaWS.RespuestaWS.listarRespuesta(BuildUp.RespuestaWS.listarRespuestaRequest request) {
            return base.Channel.listarRespuesta(request);
        }
        
        public BuildUp.RespuestaWS.respuesta[] listarRespuesta() {
            BuildUp.RespuestaWS.listarRespuestaRequest inValue = new BuildUp.RespuestaWS.listarRespuestaRequest();
            BuildUp.RespuestaWS.listarRespuestaResponse retVal = ((BuildUp.RespuestaWS.RespuestaWS)(this)).listarRespuesta(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.RespuestaWS.listarRespuestaResponse> BuildUp.RespuestaWS.RespuestaWS.listarRespuestaAsync(BuildUp.RespuestaWS.listarRespuestaRequest request) {
            return base.Channel.listarRespuestaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.RespuestaWS.listarRespuestaResponse> listarRespuestaAsync() {
            BuildUp.RespuestaWS.listarRespuestaRequest inValue = new BuildUp.RespuestaWS.listarRespuestaRequest();
            return ((BuildUp.RespuestaWS.RespuestaWS)(this)).listarRespuestaAsync(inValue);
        }
    }
}
