//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.OperarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="OperarioWS.OperarioWS")]
    public interface OperarioWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OperarioWS/actualizarOperarioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OperarioWS/actualizarOperarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OperarioWS.actualizarOperarioResponse actualizarOperario(BuildUp.OperarioWS.actualizarOperarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OperarioWS/actualizarOperarioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OperarioWS/actualizarOperarioResponse")]
        System.Threading.Tasks.Task<BuildUp.OperarioWS.actualizarOperarioResponse> actualizarOperarioAsync(BuildUp.OperarioWS.actualizarOperarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OperarioWS/eliminarOperarioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OperarioWS/eliminarOperarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OperarioWS.eliminarOperarioResponse eliminarOperario(BuildUp.OperarioWS.eliminarOperarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OperarioWS/eliminarOperarioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OperarioWS/eliminarOperarioResponse")]
        System.Threading.Tasks.Task<BuildUp.OperarioWS.eliminarOperarioResponse> eliminarOperarioAsync(BuildUp.OperarioWS.eliminarOperarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OperarioWS/insertarOperarioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OperarioWS/insertarOperarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OperarioWS.insertarOperarioResponse insertarOperario(BuildUp.OperarioWS.insertarOperarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OperarioWS/insertarOperarioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OperarioWS/insertarOperarioResponse")]
        System.Threading.Tasks.Task<BuildUp.OperarioWS.insertarOperarioResponse> insertarOperarioAsync(BuildUp.OperarioWS.insertarOperarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OperarioWS/listarOperarioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OperarioWS/listarOperarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.OperarioWS.listarOperarioResponse listarOperario(BuildUp.OperarioWS.listarOperarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/OperarioWS/listarOperarioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/OperarioWS/listarOperarioResponse")]
        System.Threading.Tasks.Task<BuildUp.OperarioWS.listarOperarioResponse> listarOperarioAsync(BuildUp.OperarioWS.listarOperarioRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class operario : persona {
        
        private lineaProduccion lineaProduccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class lineaProduccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idLineaProduccionField;
        
        private string nombreField;
        
        private operario[] operariosField;
        
        private supervisor[] supervisoresField;
        
        private tipoLadrillo tipoLadrilloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLineaProduccion {
            get {
                return this.idLineaProduccionField;
            }
            set {
                this.idLineaProduccionField = value;
                this.RaisePropertyChanged("idLineaProduccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("operarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public operario[] operarios {
            get {
                return this.operariosField;
            }
            set {
                this.operariosField = value;
                this.RaisePropertyChanged("operarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supervisores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public supervisor[] supervisores {
            get {
                return this.supervisoresField;
            }
            set {
                this.supervisoresField = value;
                this.RaisePropertyChanged("supervisores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoLadrillo tipoLadrillo {
            get {
                return this.tipoLadrilloField;
            }
            set {
                this.tipoLadrilloField = value;
                this.RaisePropertyChanged("tipoLadrillo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class supervisor : persona {
        
        private lineaProduccion lineaProduccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(supervisor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(operario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidosField;
        
        private string correoField;
        
        private System.DateTime fechaFinContratoField;
        
        private bool fechaFinContratoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonaField;
        
        private string nombresField;
        
        private string rolField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFinContrato {
            get {
                return this.fechaFinContratoField;
            }
            set {
                this.fechaFinContratoField = value;
                this.RaisePropertyChanged("fechaFinContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinContratoSpecified {
            get {
                return this.fechaFinContratoFieldSpecified;
            }
            set {
                this.fechaFinContratoFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinContratoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class tipoLadrillo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double alturaField;
        
        private double anchoField;
        
        private int idTipoLadrilloField;
        
        private double largoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
                this.RaisePropertyChanged("altura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
                this.RaisePropertyChanged("ancho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTipoLadrillo {
            get {
                return this.idTipoLadrilloField;
            }
            set {
                this.idTipoLadrilloField = value;
                this.RaisePropertyChanged("idTipoLadrillo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
                this.RaisePropertyChanged("largo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarOperario", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarOperarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.OperarioWS.operario operario;
        
        public actualizarOperarioRequest() {
        }
        
        public actualizarOperarioRequest(BuildUp.OperarioWS.operario operario) {
            this.operario = operario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarOperarioResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarOperarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarOperarioResponse() {
        }
        
        public actualizarOperarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOperario", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOperarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idOperario;
        
        public eliminarOperarioRequest() {
        }
        
        public eliminarOperarioRequest(int idOperario) {
            this.idOperario = idOperario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarOperarioResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarOperarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarOperarioResponse() {
        }
        
        public eliminarOperarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOperario", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOperarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.OperarioWS.operario operario;
        
        public insertarOperarioRequest() {
        }
        
        public insertarOperarioRequest(BuildUp.OperarioWS.operario operario) {
            this.operario = operario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarOperarioResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarOperarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarOperarioResponse() {
        }
        
        public insertarOperarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOperario", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOperarioRequest {
        
        public listarOperarioRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarOperarioResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarOperarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.OperarioWS.operario[] @return;
        
        public listarOperarioResponse() {
        }
        
        public listarOperarioResponse(BuildUp.OperarioWS.operario[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OperarioWSChannel : BuildUp.OperarioWS.OperarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OperarioWSClient : System.ServiceModel.ClientBase<BuildUp.OperarioWS.OperarioWS>, BuildUp.OperarioWS.OperarioWS {
        
        public OperarioWSClient() {
        }
        
        public OperarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OperarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OperarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OperarioWS.actualizarOperarioResponse BuildUp.OperarioWS.OperarioWS.actualizarOperario(BuildUp.OperarioWS.actualizarOperarioRequest request) {
            return base.Channel.actualizarOperario(request);
        }
        
        public int actualizarOperario(BuildUp.OperarioWS.operario operario) {
            BuildUp.OperarioWS.actualizarOperarioRequest inValue = new BuildUp.OperarioWS.actualizarOperarioRequest();
            inValue.operario = operario;
            BuildUp.OperarioWS.actualizarOperarioResponse retVal = ((BuildUp.OperarioWS.OperarioWS)(this)).actualizarOperario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OperarioWS.actualizarOperarioResponse> BuildUp.OperarioWS.OperarioWS.actualizarOperarioAsync(BuildUp.OperarioWS.actualizarOperarioRequest request) {
            return base.Channel.actualizarOperarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OperarioWS.actualizarOperarioResponse> actualizarOperarioAsync(BuildUp.OperarioWS.operario operario) {
            BuildUp.OperarioWS.actualizarOperarioRequest inValue = new BuildUp.OperarioWS.actualizarOperarioRequest();
            inValue.operario = operario;
            return ((BuildUp.OperarioWS.OperarioWS)(this)).actualizarOperarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OperarioWS.eliminarOperarioResponse BuildUp.OperarioWS.OperarioWS.eliminarOperario(BuildUp.OperarioWS.eliminarOperarioRequest request) {
            return base.Channel.eliminarOperario(request);
        }
        
        public int eliminarOperario(int idOperario) {
            BuildUp.OperarioWS.eliminarOperarioRequest inValue = new BuildUp.OperarioWS.eliminarOperarioRequest();
            inValue.idOperario = idOperario;
            BuildUp.OperarioWS.eliminarOperarioResponse retVal = ((BuildUp.OperarioWS.OperarioWS)(this)).eliminarOperario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OperarioWS.eliminarOperarioResponse> BuildUp.OperarioWS.OperarioWS.eliminarOperarioAsync(BuildUp.OperarioWS.eliminarOperarioRequest request) {
            return base.Channel.eliminarOperarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OperarioWS.eliminarOperarioResponse> eliminarOperarioAsync(int idOperario) {
            BuildUp.OperarioWS.eliminarOperarioRequest inValue = new BuildUp.OperarioWS.eliminarOperarioRequest();
            inValue.idOperario = idOperario;
            return ((BuildUp.OperarioWS.OperarioWS)(this)).eliminarOperarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OperarioWS.insertarOperarioResponse BuildUp.OperarioWS.OperarioWS.insertarOperario(BuildUp.OperarioWS.insertarOperarioRequest request) {
            return base.Channel.insertarOperario(request);
        }
        
        public int insertarOperario(BuildUp.OperarioWS.operario operario) {
            BuildUp.OperarioWS.insertarOperarioRequest inValue = new BuildUp.OperarioWS.insertarOperarioRequest();
            inValue.operario = operario;
            BuildUp.OperarioWS.insertarOperarioResponse retVal = ((BuildUp.OperarioWS.OperarioWS)(this)).insertarOperario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OperarioWS.insertarOperarioResponse> BuildUp.OperarioWS.OperarioWS.insertarOperarioAsync(BuildUp.OperarioWS.insertarOperarioRequest request) {
            return base.Channel.insertarOperarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OperarioWS.insertarOperarioResponse> insertarOperarioAsync(BuildUp.OperarioWS.operario operario) {
            BuildUp.OperarioWS.insertarOperarioRequest inValue = new BuildUp.OperarioWS.insertarOperarioRequest();
            inValue.operario = operario;
            return ((BuildUp.OperarioWS.OperarioWS)(this)).insertarOperarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.OperarioWS.listarOperarioResponse BuildUp.OperarioWS.OperarioWS.listarOperario(BuildUp.OperarioWS.listarOperarioRequest request) {
            return base.Channel.listarOperario(request);
        }
        
        public BuildUp.OperarioWS.operario[] listarOperario() {
            BuildUp.OperarioWS.listarOperarioRequest inValue = new BuildUp.OperarioWS.listarOperarioRequest();
            BuildUp.OperarioWS.listarOperarioResponse retVal = ((BuildUp.OperarioWS.OperarioWS)(this)).listarOperario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.OperarioWS.listarOperarioResponse> BuildUp.OperarioWS.OperarioWS.listarOperarioAsync(BuildUp.OperarioWS.listarOperarioRequest request) {
            return base.Channel.listarOperarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.OperarioWS.listarOperarioResponse> listarOperarioAsync() {
            BuildUp.OperarioWS.listarOperarioRequest inValue = new BuildUp.OperarioWS.listarOperarioRequest();
            return ((BuildUp.OperarioWS.OperarioWS)(this)).listarOperarioAsync(inValue);
        }
    }
}
