//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.RegistroMermaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="RegistroMermaWS.RegistroMermaWS")]
    public interface RegistroMermaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RegistroMermaWS/listarRegistroMermaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RegistroMermaWS/listarRegistroMermaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.RegistroMermaWS.listarRegistroMermaResponse listarRegistroMerma(BuildUp.RegistroMermaWS.listarRegistroMermaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RegistroMermaWS/listarRegistroMermaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RegistroMermaWS/listarRegistroMermaResponse")]
        System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.listarRegistroMermaResponse> listarRegistroMermaAsync(BuildUp.RegistroMermaWS.listarRegistroMermaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RegistroMermaWS/actualizarRegistroMermaReques" +
            "t", ReplyAction="http://services.buildup.pucp.edu.pe/RegistroMermaWS/actualizarRegistroMermaRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.RegistroMermaWS.actualizarRegistroMermaResponse actualizarRegistroMerma(BuildUp.RegistroMermaWS.actualizarRegistroMermaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RegistroMermaWS/actualizarRegistroMermaReques" +
            "t", ReplyAction="http://services.buildup.pucp.edu.pe/RegistroMermaWS/actualizarRegistroMermaRespon" +
            "se")]
        System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.actualizarRegistroMermaResponse> actualizarRegistroMermaAsync(BuildUp.RegistroMermaWS.actualizarRegistroMermaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RegistroMermaWS/eliminarRegistroMermaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RegistroMermaWS/eliminarRegistroMermaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.RegistroMermaWS.eliminarRegistroMermaResponse eliminarRegistroMerma(BuildUp.RegistroMermaWS.eliminarRegistroMermaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RegistroMermaWS/eliminarRegistroMermaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RegistroMermaWS/eliminarRegistroMermaResponse" +
            "")]
        System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.eliminarRegistroMermaResponse> eliminarRegistroMermaAsync(BuildUp.RegistroMermaWS.eliminarRegistroMermaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RegistroMermaWS/insertarRegistroMermaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RegistroMermaWS/insertarRegistroMermaResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.RegistroMermaWS.insertarRegistroMermaResponse insertarRegistroMerma(BuildUp.RegistroMermaWS.insertarRegistroMermaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/RegistroMermaWS/insertarRegistroMermaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/RegistroMermaWS/insertarRegistroMermaResponse" +
            "")]
        System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.insertarRegistroMermaResponse> insertarRegistroMermaAsync(BuildUp.RegistroMermaWS.insertarRegistroMermaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class registroMerma : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int cantidadField;
        
        private System.DateTime fechaField;
        
        private bool fechaFieldSpecified;
        
        private int idRegistroMermaField;
        
        private lineaProduccion lineaProduccionField;
        
        private merma mermaField;
        
        private supervisor supervisorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int cantidad {
            get {
                return this.cantidadField;
            }
            set {
                this.cantidadField = value;
                this.RaisePropertyChanged("cantidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("fecha");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaSpecified {
            get {
                return this.fechaFieldSpecified;
            }
            set {
                this.fechaFieldSpecified = value;
                this.RaisePropertyChanged("fechaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idRegistroMerma {
            get {
                return this.idRegistroMermaField;
            }
            set {
                this.idRegistroMermaField = value;
                this.RaisePropertyChanged("idRegistroMerma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public merma merma {
            get {
                return this.mermaField;
            }
            set {
                this.mermaField = value;
                this.RaisePropertyChanged("merma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public supervisor supervisor {
            get {
                return this.supervisorField;
            }
            set {
                this.supervisorField = value;
                this.RaisePropertyChanged("supervisor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class lineaProduccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idLineaProduccionField;
        
        private string nombreField;
        
        private operario[] operariosField;
        
        private supervisor[] supervisoresField;
        
        private tipoLadrillo tipoLadrilloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLineaProduccion {
            get {
                return this.idLineaProduccionField;
            }
            set {
                this.idLineaProduccionField = value;
                this.RaisePropertyChanged("idLineaProduccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("operarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public operario[] operarios {
            get {
                return this.operariosField;
            }
            set {
                this.operariosField = value;
                this.RaisePropertyChanged("operarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supervisores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public supervisor[] supervisores {
            get {
                return this.supervisoresField;
            }
            set {
                this.supervisoresField = value;
                this.RaisePropertyChanged("supervisores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoLadrillo tipoLadrillo {
            get {
                return this.tipoLadrilloField;
            }
            set {
                this.tipoLadrilloField = value;
                this.RaisePropertyChanged("tipoLadrillo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class operario : persona {
        
        private lineaProduccion lineaProduccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(supervisor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(operario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidosField;
        
        private string correoField;
        
        private System.DateTime fechaFinContratoField;
        
        private bool fechaFinContratoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonaField;
        
        private string nombresField;
        
        private string rolField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFinContrato {
            get {
                return this.fechaFinContratoField;
            }
            set {
                this.fechaFinContratoField = value;
                this.RaisePropertyChanged("fechaFinContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinContratoSpecified {
            get {
                return this.fechaFinContratoFieldSpecified;
            }
            set {
                this.fechaFinContratoFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinContratoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class merma : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idMermaField;
        
        private string tipoField;
        
        private string unidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idMerma {
            get {
                return this.idMermaField;
            }
            set {
                this.idMermaField = value;
                this.RaisePropertyChanged("idMerma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string unidad {
            get {
                return this.unidadField;
            }
            set {
                this.unidadField = value;
                this.RaisePropertyChanged("unidad");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class tipoLadrillo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double alturaField;
        
        private double anchoField;
        
        private int idTipoLadrilloField;
        
        private double largoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
                this.RaisePropertyChanged("altura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
                this.RaisePropertyChanged("ancho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTipoLadrillo {
            get {
                return this.idTipoLadrilloField;
            }
            set {
                this.idTipoLadrilloField = value;
                this.RaisePropertyChanged("idTipoLadrillo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
                this.RaisePropertyChanged("largo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class supervisor : persona {
        
        private lineaProduccion lineaProduccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarRegistroMerma", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRegistroMermaRequest {
        
        public listarRegistroMermaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarRegistroMermaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRegistroMermaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.RegistroMermaWS.registroMerma[] @return;
        
        public listarRegistroMermaResponse() {
        }
        
        public listarRegistroMermaResponse(BuildUp.RegistroMermaWS.registroMerma[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarRegistroMerma", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarRegistroMermaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.RegistroMermaWS.registroMerma registroMerma;
        
        public actualizarRegistroMermaRequest() {
        }
        
        public actualizarRegistroMermaRequest(BuildUp.RegistroMermaWS.registroMerma registroMerma) {
            this.registroMerma = registroMerma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarRegistroMermaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarRegistroMermaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarRegistroMermaResponse() {
        }
        
        public actualizarRegistroMermaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRegistroMerma", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRegistroMermaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idRegistroMerma;
        
        public eliminarRegistroMermaRequest() {
        }
        
        public eliminarRegistroMermaRequest(int idRegistroMerma) {
            this.idRegistroMerma = idRegistroMerma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarRegistroMermaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRegistroMermaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarRegistroMermaResponse() {
        }
        
        public eliminarRegistroMermaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRegistroMerma", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRegistroMermaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.RegistroMermaWS.registroMerma registroMerma;
        
        public insertarRegistroMermaRequest() {
        }
        
        public insertarRegistroMermaRequest(BuildUp.RegistroMermaWS.registroMerma registroMerma) {
            this.registroMerma = registroMerma;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarRegistroMermaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRegistroMermaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarRegistroMermaResponse() {
        }
        
        public insertarRegistroMermaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegistroMermaWSChannel : BuildUp.RegistroMermaWS.RegistroMermaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegistroMermaWSClient : System.ServiceModel.ClientBase<BuildUp.RegistroMermaWS.RegistroMermaWS>, BuildUp.RegistroMermaWS.RegistroMermaWS {
        
        public RegistroMermaWSClient() {
        }
        
        public RegistroMermaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegistroMermaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroMermaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegistroMermaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.RegistroMermaWS.listarRegistroMermaResponse BuildUp.RegistroMermaWS.RegistroMermaWS.listarRegistroMerma(BuildUp.RegistroMermaWS.listarRegistroMermaRequest request) {
            return base.Channel.listarRegistroMerma(request);
        }
        
        public BuildUp.RegistroMermaWS.registroMerma[] listarRegistroMerma() {
            BuildUp.RegistroMermaWS.listarRegistroMermaRequest inValue = new BuildUp.RegistroMermaWS.listarRegistroMermaRequest();
            BuildUp.RegistroMermaWS.listarRegistroMermaResponse retVal = ((BuildUp.RegistroMermaWS.RegistroMermaWS)(this)).listarRegistroMerma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.listarRegistroMermaResponse> BuildUp.RegistroMermaWS.RegistroMermaWS.listarRegistroMermaAsync(BuildUp.RegistroMermaWS.listarRegistroMermaRequest request) {
            return base.Channel.listarRegistroMermaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.listarRegistroMermaResponse> listarRegistroMermaAsync() {
            BuildUp.RegistroMermaWS.listarRegistroMermaRequest inValue = new BuildUp.RegistroMermaWS.listarRegistroMermaRequest();
            return ((BuildUp.RegistroMermaWS.RegistroMermaWS)(this)).listarRegistroMermaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.RegistroMermaWS.actualizarRegistroMermaResponse BuildUp.RegistroMermaWS.RegistroMermaWS.actualizarRegistroMerma(BuildUp.RegistroMermaWS.actualizarRegistroMermaRequest request) {
            return base.Channel.actualizarRegistroMerma(request);
        }
        
        public int actualizarRegistroMerma(BuildUp.RegistroMermaWS.registroMerma registroMerma) {
            BuildUp.RegistroMermaWS.actualizarRegistroMermaRequest inValue = new BuildUp.RegistroMermaWS.actualizarRegistroMermaRequest();
            inValue.registroMerma = registroMerma;
            BuildUp.RegistroMermaWS.actualizarRegistroMermaResponse retVal = ((BuildUp.RegistroMermaWS.RegistroMermaWS)(this)).actualizarRegistroMerma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.actualizarRegistroMermaResponse> BuildUp.RegistroMermaWS.RegistroMermaWS.actualizarRegistroMermaAsync(BuildUp.RegistroMermaWS.actualizarRegistroMermaRequest request) {
            return base.Channel.actualizarRegistroMermaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.actualizarRegistroMermaResponse> actualizarRegistroMermaAsync(BuildUp.RegistroMermaWS.registroMerma registroMerma) {
            BuildUp.RegistroMermaWS.actualizarRegistroMermaRequest inValue = new BuildUp.RegistroMermaWS.actualizarRegistroMermaRequest();
            inValue.registroMerma = registroMerma;
            return ((BuildUp.RegistroMermaWS.RegistroMermaWS)(this)).actualizarRegistroMermaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.RegistroMermaWS.eliminarRegistroMermaResponse BuildUp.RegistroMermaWS.RegistroMermaWS.eliminarRegistroMerma(BuildUp.RegistroMermaWS.eliminarRegistroMermaRequest request) {
            return base.Channel.eliminarRegistroMerma(request);
        }
        
        public int eliminarRegistroMerma(int idRegistroMerma) {
            BuildUp.RegistroMermaWS.eliminarRegistroMermaRequest inValue = new BuildUp.RegistroMermaWS.eliminarRegistroMermaRequest();
            inValue.idRegistroMerma = idRegistroMerma;
            BuildUp.RegistroMermaWS.eliminarRegistroMermaResponse retVal = ((BuildUp.RegistroMermaWS.RegistroMermaWS)(this)).eliminarRegistroMerma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.eliminarRegistroMermaResponse> BuildUp.RegistroMermaWS.RegistroMermaWS.eliminarRegistroMermaAsync(BuildUp.RegistroMermaWS.eliminarRegistroMermaRequest request) {
            return base.Channel.eliminarRegistroMermaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.eliminarRegistroMermaResponse> eliminarRegistroMermaAsync(int idRegistroMerma) {
            BuildUp.RegistroMermaWS.eliminarRegistroMermaRequest inValue = new BuildUp.RegistroMermaWS.eliminarRegistroMermaRequest();
            inValue.idRegistroMerma = idRegistroMerma;
            return ((BuildUp.RegistroMermaWS.RegistroMermaWS)(this)).eliminarRegistroMermaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.RegistroMermaWS.insertarRegistroMermaResponse BuildUp.RegistroMermaWS.RegistroMermaWS.insertarRegistroMerma(BuildUp.RegistroMermaWS.insertarRegistroMermaRequest request) {
            return base.Channel.insertarRegistroMerma(request);
        }
        
        public int insertarRegistroMerma(BuildUp.RegistroMermaWS.registroMerma registroMerma) {
            BuildUp.RegistroMermaWS.insertarRegistroMermaRequest inValue = new BuildUp.RegistroMermaWS.insertarRegistroMermaRequest();
            inValue.registroMerma = registroMerma;
            BuildUp.RegistroMermaWS.insertarRegistroMermaResponse retVal = ((BuildUp.RegistroMermaWS.RegistroMermaWS)(this)).insertarRegistroMerma(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.insertarRegistroMermaResponse> BuildUp.RegistroMermaWS.RegistroMermaWS.insertarRegistroMermaAsync(BuildUp.RegistroMermaWS.insertarRegistroMermaRequest request) {
            return base.Channel.insertarRegistroMermaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.RegistroMermaWS.insertarRegistroMermaResponse> insertarRegistroMermaAsync(BuildUp.RegistroMermaWS.registroMerma registroMerma) {
            BuildUp.RegistroMermaWS.insertarRegistroMermaRequest inValue = new BuildUp.RegistroMermaWS.insertarRegistroMermaRequest();
            inValue.registroMerma = registroMerma;
            return ((BuildUp.RegistroMermaWS.RegistroMermaWS)(this)).insertarRegistroMermaAsync(inValue);
        }
    }
}
