//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.ReporteIncidenciaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="ReporteIncidenciaWS.ReportesIncidencia")]
    public interface ReportesIncidencia {
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.buildup.pucp.edu.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/ReportesIncidencia/generarReporteIncidenciaRe" +
            "quest", ReplyAction="http://services.buildup.pucp.edu.pe/ReportesIncidencia/generarReporteIncidenciaRe" +
            "sponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaResponse generarReporteIncidencia(BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/ReportesIncidencia/generarReporteIncidenciaRe" +
            "quest", ReplyAction="http://services.buildup.pucp.edu.pe/ReportesIncidencia/generarReporteIncidenciaRe" +
            "sponse")]
        System.Threading.Tasks.Task<BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaResponse> generarReporteIncidenciaAsync(BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteIncidencia", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteIncidenciaRequest {
        
        public generarReporteIncidenciaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteIncidenciaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteIncidenciaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public generarReporteIncidenciaResponse() {
        }
        
        public generarReporteIncidenciaResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportesIncidenciaChannel : BuildUp.ReporteIncidenciaWS.ReportesIncidencia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportesIncidenciaClient : System.ServiceModel.ClientBase<BuildUp.ReporteIncidenciaWS.ReportesIncidencia>, BuildUp.ReporteIncidenciaWS.ReportesIncidencia {
        
        public ReportesIncidenciaClient() {
        }
        
        public ReportesIncidenciaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportesIncidenciaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesIncidenciaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesIncidenciaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaResponse BuildUp.ReporteIncidenciaWS.ReportesIncidencia.generarReporteIncidencia(BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaRequest request) {
            return base.Channel.generarReporteIncidencia(request);
        }
        
        public byte[] generarReporteIncidencia() {
            BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaRequest inValue = new BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaRequest();
            BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaResponse retVal = ((BuildUp.ReporteIncidenciaWS.ReportesIncidencia)(this)).generarReporteIncidencia(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaResponse> BuildUp.ReporteIncidenciaWS.ReportesIncidencia.generarReporteIncidenciaAsync(BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaRequest request) {
            return base.Channel.generarReporteIncidenciaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaResponse> generarReporteIncidenciaAsync() {
            BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaRequest inValue = new BuildUp.ReporteIncidenciaWS.generarReporteIncidenciaRequest();
            return ((BuildUp.ReporteIncidenciaWS.ReportesIncidencia)(this)).generarReporteIncidenciaAsync(inValue);
        }
    }
}
