//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.JefeAreaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="JefeAreaWS.JefeAreaWS")]
    public interface JefeAreaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/listarJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/listarJefeAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.JefeAreaWS.listarJefeAreaResponse listarJefeArea(BuildUp.JefeAreaWS.listarJefeAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/listarJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/listarJefeAreaResponse")]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.listarJefeAreaResponse> listarJefeAreaAsync(BuildUp.JefeAreaWS.listarJefeAreaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/insertarJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/insertarJefeAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.JefeAreaWS.insertarJefeAreaResponse insertarJefeArea(BuildUp.JefeAreaWS.insertarJefeAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/insertarJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/insertarJefeAreaResponse")]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.insertarJefeAreaResponse> insertarJefeAreaAsync(BuildUp.JefeAreaWS.insertarJefeAreaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/eliminarJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/eliminarJefeAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.JefeAreaWS.eliminarJefeAreaResponse eliminarJefeArea(BuildUp.JefeAreaWS.eliminarJefeAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/eliminarJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/eliminarJefeAreaResponse")]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.eliminarJefeAreaResponse> eliminarJefeAreaAsync(BuildUp.JefeAreaWS.eliminarJefeAreaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/obtenerFotoFirmaJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/obtenerFotoFirmaJefeAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaResponse obtenerFotoFirmaJefeArea(BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/obtenerFotoFirmaJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/obtenerFotoFirmaJefeAreaResponse")]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaResponse> obtenerFotoFirmaJefeAreaAsync(BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/modificarJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/modificarJefeAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.JefeAreaWS.modificarJefeAreaResponse modificarJefeArea(BuildUp.JefeAreaWS.modificarJefeAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/modificarJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/modificarJefeAreaResponse")]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.modificarJefeAreaResponse> modificarJefeAreaAsync(BuildUp.JefeAreaWS.modificarJefeAreaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/actualizarEstadoJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/actualizarEstadoJefeAreaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.JefeAreaWS.actualizarEstadoJefeAreaResponse actualizarEstadoJefeArea(BuildUp.JefeAreaWS.actualizarEstadoJefeAreaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/JefeAreaWS/actualizarEstadoJefeAreaRequest", ReplyAction="http://services.buildup.pucp.edu.pe/JefeAreaWS/actualizarEstadoJefeAreaResponse")]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.actualizarEstadoJefeAreaResponse> actualizarEstadoJefeAreaAsync(BuildUp.JefeAreaWS.actualizarEstadoJefeAreaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class jefeArea : persona {
        
        private string archivoFirmaDigitalField;
        
        private byte[] foto_firmaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string archivoFirmaDigital {
            get {
                return this.archivoFirmaDigitalField;
            }
            set {
                this.archivoFirmaDigitalField = value;
                this.RaisePropertyChanged("archivoFirmaDigital");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] foto_firma {
            get {
                return this.foto_firmaField;
            }
            set {
                this.foto_firmaField = value;
                this.RaisePropertyChanged("foto_firma");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(jefeArea))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidosField;
        
        private string correoField;
        
        private System.DateTime fechaFinContratoField;
        
        private bool fechaFinContratoFieldSpecified;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonaField;
        
        private string nombresField;
        
        private string rolField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFinContrato {
            get {
                return this.fechaFinContratoField;
            }
            set {
                this.fechaFinContratoField = value;
                this.RaisePropertyChanged("fechaFinContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinContratoSpecified {
            get {
                return this.fechaFinContratoFieldSpecified;
            }
            set {
                this.fechaFinContratoFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinContratoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarJefeArea", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarJefeAreaRequest {
        
        public listarJefeAreaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarJefeAreaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarJefeAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.JefeAreaWS.jefeArea[] @return;
        
        public listarJefeAreaResponse() {
        }
        
        public listarJefeAreaResponse(BuildUp.JefeAreaWS.jefeArea[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarJefeArea", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarJefeAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.JefeAreaWS.jefeArea jefeArea;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string password;
        
        public insertarJefeAreaRequest() {
        }
        
        public insertarJefeAreaRequest(BuildUp.JefeAreaWS.jefeArea jefeArea, string username, string password) {
            this.jefeArea = jefeArea;
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarJefeAreaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarJefeAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarJefeAreaResponse() {
        }
        
        public insertarJefeAreaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarJefeArea", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarJefeAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idJefeArea;
        
        public eliminarJefeAreaRequest() {
        }
        
        public eliminarJefeAreaRequest(int idJefeArea) {
            this.idJefeArea = idJefeArea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarJefeAreaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarJefeAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarJefeAreaResponse() {
        }
        
        public eliminarJefeAreaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerFotoFirmaJefeArea", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerFotoFirmaJefeAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idJefeArea;
        
        public obtenerFotoFirmaJefeAreaRequest() {
        }
        
        public obtenerFotoFirmaJefeAreaRequest(int idJefeArea) {
            this.idJefeArea = idJefeArea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerFotoFirmaJefeAreaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerFotoFirmaJefeAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public obtenerFotoFirmaJefeAreaResponse() {
        }
        
        public obtenerFotoFirmaJefeAreaResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarJefeArea", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarJefeAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.JefeAreaWS.jefeArea jefeArea;
        
        public modificarJefeAreaRequest() {
        }
        
        public modificarJefeAreaRequest(BuildUp.JefeAreaWS.jefeArea jefeArea) {
            this.jefeArea = jefeArea;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarJefeAreaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarJefeAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarJefeAreaResponse() {
        }
        
        public modificarJefeAreaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstadoJefeArea", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEstadoJefeAreaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPersona;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public actualizarEstadoJefeAreaRequest() {
        }
        
        public actualizarEstadoJefeAreaRequest(int idPersona, bool activo) {
            this.idPersona = idPersona;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstadoJefeAreaResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEstadoJefeAreaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarEstadoJefeAreaResponse() {
        }
        
        public actualizarEstadoJefeAreaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JefeAreaWSChannel : BuildUp.JefeAreaWS.JefeAreaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JefeAreaWSClient : System.ServiceModel.ClientBase<BuildUp.JefeAreaWS.JefeAreaWS>, BuildUp.JefeAreaWS.JefeAreaWS {
        
        public JefeAreaWSClient() {
        }
        
        public JefeAreaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JefeAreaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JefeAreaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JefeAreaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.JefeAreaWS.listarJefeAreaResponse BuildUp.JefeAreaWS.JefeAreaWS.listarJefeArea(BuildUp.JefeAreaWS.listarJefeAreaRequest request) {
            return base.Channel.listarJefeArea(request);
        }
        
        public BuildUp.JefeAreaWS.jefeArea[] listarJefeArea() {
            BuildUp.JefeAreaWS.listarJefeAreaRequest inValue = new BuildUp.JefeAreaWS.listarJefeAreaRequest();
            BuildUp.JefeAreaWS.listarJefeAreaResponse retVal = ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).listarJefeArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.listarJefeAreaResponse> BuildUp.JefeAreaWS.JefeAreaWS.listarJefeAreaAsync(BuildUp.JefeAreaWS.listarJefeAreaRequest request) {
            return base.Channel.listarJefeAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.JefeAreaWS.listarJefeAreaResponse> listarJefeAreaAsync() {
            BuildUp.JefeAreaWS.listarJefeAreaRequest inValue = new BuildUp.JefeAreaWS.listarJefeAreaRequest();
            return ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).listarJefeAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.JefeAreaWS.insertarJefeAreaResponse BuildUp.JefeAreaWS.JefeAreaWS.insertarJefeArea(BuildUp.JefeAreaWS.insertarJefeAreaRequest request) {
            return base.Channel.insertarJefeArea(request);
        }
        
        public int insertarJefeArea(BuildUp.JefeAreaWS.jefeArea jefeArea, string username, string password) {
            BuildUp.JefeAreaWS.insertarJefeAreaRequest inValue = new BuildUp.JefeAreaWS.insertarJefeAreaRequest();
            inValue.jefeArea = jefeArea;
            inValue.username = username;
            inValue.password = password;
            BuildUp.JefeAreaWS.insertarJefeAreaResponse retVal = ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).insertarJefeArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.insertarJefeAreaResponse> BuildUp.JefeAreaWS.JefeAreaWS.insertarJefeAreaAsync(BuildUp.JefeAreaWS.insertarJefeAreaRequest request) {
            return base.Channel.insertarJefeAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.JefeAreaWS.insertarJefeAreaResponse> insertarJefeAreaAsync(BuildUp.JefeAreaWS.jefeArea jefeArea, string username, string password) {
            BuildUp.JefeAreaWS.insertarJefeAreaRequest inValue = new BuildUp.JefeAreaWS.insertarJefeAreaRequest();
            inValue.jefeArea = jefeArea;
            inValue.username = username;
            inValue.password = password;
            return ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).insertarJefeAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.JefeAreaWS.eliminarJefeAreaResponse BuildUp.JefeAreaWS.JefeAreaWS.eliminarJefeArea(BuildUp.JefeAreaWS.eliminarJefeAreaRequest request) {
            return base.Channel.eliminarJefeArea(request);
        }
        
        public int eliminarJefeArea(int idJefeArea) {
            BuildUp.JefeAreaWS.eliminarJefeAreaRequest inValue = new BuildUp.JefeAreaWS.eliminarJefeAreaRequest();
            inValue.idJefeArea = idJefeArea;
            BuildUp.JefeAreaWS.eliminarJefeAreaResponse retVal = ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).eliminarJefeArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.eliminarJefeAreaResponse> BuildUp.JefeAreaWS.JefeAreaWS.eliminarJefeAreaAsync(BuildUp.JefeAreaWS.eliminarJefeAreaRequest request) {
            return base.Channel.eliminarJefeAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.JefeAreaWS.eliminarJefeAreaResponse> eliminarJefeAreaAsync(int idJefeArea) {
            BuildUp.JefeAreaWS.eliminarJefeAreaRequest inValue = new BuildUp.JefeAreaWS.eliminarJefeAreaRequest();
            inValue.idJefeArea = idJefeArea;
            return ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).eliminarJefeAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaResponse BuildUp.JefeAreaWS.JefeAreaWS.obtenerFotoFirmaJefeArea(BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaRequest request) {
            return base.Channel.obtenerFotoFirmaJefeArea(request);
        }
        
        public byte[] obtenerFotoFirmaJefeArea(int idJefeArea) {
            BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaRequest inValue = new BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaRequest();
            inValue.idJefeArea = idJefeArea;
            BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaResponse retVal = ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).obtenerFotoFirmaJefeArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaResponse> BuildUp.JefeAreaWS.JefeAreaWS.obtenerFotoFirmaJefeAreaAsync(BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaRequest request) {
            return base.Channel.obtenerFotoFirmaJefeAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaResponse> obtenerFotoFirmaJefeAreaAsync(int idJefeArea) {
            BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaRequest inValue = new BuildUp.JefeAreaWS.obtenerFotoFirmaJefeAreaRequest();
            inValue.idJefeArea = idJefeArea;
            return ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).obtenerFotoFirmaJefeAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.JefeAreaWS.modificarJefeAreaResponse BuildUp.JefeAreaWS.JefeAreaWS.modificarJefeArea(BuildUp.JefeAreaWS.modificarJefeAreaRequest request) {
            return base.Channel.modificarJefeArea(request);
        }
        
        public int modificarJefeArea(BuildUp.JefeAreaWS.jefeArea jefeArea) {
            BuildUp.JefeAreaWS.modificarJefeAreaRequest inValue = new BuildUp.JefeAreaWS.modificarJefeAreaRequest();
            inValue.jefeArea = jefeArea;
            BuildUp.JefeAreaWS.modificarJefeAreaResponse retVal = ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).modificarJefeArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.modificarJefeAreaResponse> BuildUp.JefeAreaWS.JefeAreaWS.modificarJefeAreaAsync(BuildUp.JefeAreaWS.modificarJefeAreaRequest request) {
            return base.Channel.modificarJefeAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.JefeAreaWS.modificarJefeAreaResponse> modificarJefeAreaAsync(BuildUp.JefeAreaWS.jefeArea jefeArea) {
            BuildUp.JefeAreaWS.modificarJefeAreaRequest inValue = new BuildUp.JefeAreaWS.modificarJefeAreaRequest();
            inValue.jefeArea = jefeArea;
            return ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).modificarJefeAreaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.JefeAreaWS.actualizarEstadoJefeAreaResponse BuildUp.JefeAreaWS.JefeAreaWS.actualizarEstadoJefeArea(BuildUp.JefeAreaWS.actualizarEstadoJefeAreaRequest request) {
            return base.Channel.actualizarEstadoJefeArea(request);
        }
        
        public int actualizarEstadoJefeArea(int idPersona, bool activo) {
            BuildUp.JefeAreaWS.actualizarEstadoJefeAreaRequest inValue = new BuildUp.JefeAreaWS.actualizarEstadoJefeAreaRequest();
            inValue.idPersona = idPersona;
            inValue.activo = activo;
            BuildUp.JefeAreaWS.actualizarEstadoJefeAreaResponse retVal = ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).actualizarEstadoJefeArea(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.JefeAreaWS.actualizarEstadoJefeAreaResponse> BuildUp.JefeAreaWS.JefeAreaWS.actualizarEstadoJefeAreaAsync(BuildUp.JefeAreaWS.actualizarEstadoJefeAreaRequest request) {
            return base.Channel.actualizarEstadoJefeAreaAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.JefeAreaWS.actualizarEstadoJefeAreaResponse> actualizarEstadoJefeAreaAsync(int idPersona, bool activo) {
            BuildUp.JefeAreaWS.actualizarEstadoJefeAreaRequest inValue = new BuildUp.JefeAreaWS.actualizarEstadoJefeAreaRequest();
            inValue.idPersona = idPersona;
            inValue.activo = activo;
            return ((BuildUp.JefeAreaWS.JefeAreaWS)(this)).actualizarEstadoJefeAreaAsync(inValue);
        }
    }
}
