//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.ReportesProduccionWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="date", Namespace="http://services.buildup.pucp.edu.pe/")]
    [System.SerializableAttribute()]
    public partial class date : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="ReportesProduccionWS.ReportesProduccion")]
    public interface ReportesProduccion {
        
        // CODEGEN: Generating message contract since element name fecha from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/ReportesProduccion/generarReporteProduccionDi" +
            "arioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/ReportesProduccion/generarReporteProduccionDi" +
            "arioResponse")]
        BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioResponse generarReporteProduccionDiario(BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/ReportesProduccion/generarReporteProduccionDi" +
            "arioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/ReportesProduccion/generarReporteProduccionDi" +
            "arioResponse")]
        System.Threading.Tasks.Task<BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioResponse> generarReporteProduccionDiarioAsync(BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequest request);
        
        // CODEGEN: Generating message contract since message part namespace () does not match the default value (http://services.buildup.pucp.edu.pe/)
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/ReportesProduccion/generarReporteProduccionMe" +
            "nsualRequest", ReplyAction="http://services.buildup.pucp.edu.pe/ReportesProduccion/generarReporteProduccionMe" +
            "nsualResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.ReportesProduccionWS.generarReporteProduccionMensualResponse generarReporteProduccionMensual(BuildUp.ReportesProduccionWS.generarReporteProduccionMensualRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/ReportesProduccion/generarReporteProduccionMe" +
            "nsualRequest", ReplyAction="http://services.buildup.pucp.edu.pe/ReportesProduccion/generarReporteProduccionMe" +
            "nsualResponse")]
        System.Threading.Tasks.Task<BuildUp.ReportesProduccionWS.generarReporteProduccionMensualResponse> generarReporteProduccionMensualAsync(BuildUp.ReportesProduccionWS.generarReporteProduccionMensualRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReporteProduccionDiarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReporteProduccionDiario", Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        public BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequestBody Body;
        
        public generarReporteProduccionDiarioRequest() {
        }
        
        public generarReporteProduccionDiarioRequest(BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReporteProduccionDiarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BuildUp.ReportesProduccionWS.date fecha;
        
        public generarReporteProduccionDiarioRequestBody() {
        }
        
        public generarReporteProduccionDiarioRequestBody(BuildUp.ReportesProduccionWS.date fecha) {
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class generarReporteProduccionDiarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="generarReporteProduccionDiarioResponse", Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        public BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioResponseBody Body;
        
        public generarReporteProduccionDiarioResponse() {
        }
        
        public generarReporteProduccionDiarioResponse(BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class generarReporteProduccionDiarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public byte[] @return;
        
        public generarReporteProduccionDiarioResponseBody() {
        }
        
        public generarReporteProduccionDiarioResponseBody(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteProduccionMensual", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteProduccionMensualRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int mes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int anho;
        
        public generarReporteProduccionMensualRequest() {
        }
        
        public generarReporteProduccionMensualRequest(int mes, int anho) {
            this.mes = mes;
            this.anho = anho;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generarReporteProduccionMensualResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class generarReporteProduccionMensualResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public generarReporteProduccionMensualResponse() {
        }
        
        public generarReporteProduccionMensualResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReportesProduccionChannel : BuildUp.ReportesProduccionWS.ReportesProduccion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportesProduccionClient : System.ServiceModel.ClientBase<BuildUp.ReportesProduccionWS.ReportesProduccion>, BuildUp.ReportesProduccionWS.ReportesProduccion {
        
        public ReportesProduccionClient() {
        }
        
        public ReportesProduccionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportesProduccionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesProduccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesProduccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioResponse BuildUp.ReportesProduccionWS.ReportesProduccion.generarReporteProduccionDiario(BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequest request) {
            return base.Channel.generarReporteProduccionDiario(request);
        }
        
        public byte[] generarReporteProduccionDiario(BuildUp.ReportesProduccionWS.date fecha) {
            BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequest inValue = new BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequest();
            inValue.Body = new BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequestBody();
            inValue.Body.fecha = fecha;
            BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioResponse retVal = ((BuildUp.ReportesProduccionWS.ReportesProduccion)(this)).generarReporteProduccionDiario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioResponse> BuildUp.ReportesProduccionWS.ReportesProduccion.generarReporteProduccionDiarioAsync(BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequest request) {
            return base.Channel.generarReporteProduccionDiarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioResponse> generarReporteProduccionDiarioAsync(BuildUp.ReportesProduccionWS.date fecha) {
            BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequest inValue = new BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequest();
            inValue.Body = new BuildUp.ReportesProduccionWS.generarReporteProduccionDiarioRequestBody();
            inValue.Body.fecha = fecha;
            return ((BuildUp.ReportesProduccionWS.ReportesProduccion)(this)).generarReporteProduccionDiarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.ReportesProduccionWS.generarReporteProduccionMensualResponse BuildUp.ReportesProduccionWS.ReportesProduccion.generarReporteProduccionMensual(BuildUp.ReportesProduccionWS.generarReporteProduccionMensualRequest request) {
            return base.Channel.generarReporteProduccionMensual(request);
        }
        
        public byte[] generarReporteProduccionMensual(int mes, int anho) {
            BuildUp.ReportesProduccionWS.generarReporteProduccionMensualRequest inValue = new BuildUp.ReportesProduccionWS.generarReporteProduccionMensualRequest();
            inValue.mes = mes;
            inValue.anho = anho;
            BuildUp.ReportesProduccionWS.generarReporteProduccionMensualResponse retVal = ((BuildUp.ReportesProduccionWS.ReportesProduccion)(this)).generarReporteProduccionMensual(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.ReportesProduccionWS.generarReporteProduccionMensualResponse> BuildUp.ReportesProduccionWS.ReportesProduccion.generarReporteProduccionMensualAsync(BuildUp.ReportesProduccionWS.generarReporteProduccionMensualRequest request) {
            return base.Channel.generarReporteProduccionMensualAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.ReportesProduccionWS.generarReporteProduccionMensualResponse> generarReporteProduccionMensualAsync(int mes, int anho) {
            BuildUp.ReportesProduccionWS.generarReporteProduccionMensualRequest inValue = new BuildUp.ReportesProduccionWS.generarReporteProduccionMensualRequest();
            inValue.mes = mes;
            inValue.anho = anho;
            return ((BuildUp.ReportesProduccionWS.ReportesProduccion)(this)).generarReporteProduccionMensualAsync(inValue);
        }
    }
}
