//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.UsuarioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="UsuarioWS.UsuarioWS")]
    public interface UsuarioWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/UsuarioWS/autenticarUsuarioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/UsuarioWS/autenticarUsuarioResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.UsuarioWS.autenticarUsuarioResponse autenticarUsuario(BuildUp.UsuarioWS.autenticarUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/UsuarioWS/autenticarUsuarioRequest", ReplyAction="http://services.buildup.pucp.edu.pe/UsuarioWS/autenticarUsuarioResponse")]
        System.Threading.Tasks.Task<BuildUp.UsuarioWS.autenticarUsuarioResponse> autenticarUsuarioAsync(BuildUp.UsuarioWS.autenticarUsuarioRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/UsuarioWS/buscarUsuarioPorUsernameRequest", ReplyAction="http://services.buildup.pucp.edu.pe/UsuarioWS/buscarUsuarioPorUsernameResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.UsuarioWS.buscarUsuarioPorUsernameResponse buscarUsuarioPorUsername(BuildUp.UsuarioWS.buscarUsuarioPorUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/UsuarioWS/buscarUsuarioPorUsernameRequest", ReplyAction="http://services.buildup.pucp.edu.pe/UsuarioWS/buscarUsuarioPorUsernameResponse")]
        System.Threading.Tasks.Task<BuildUp.UsuarioWS.buscarUsuarioPorUsernameResponse> buscarUsuarioPorUsernameAsync(BuildUp.UsuarioWS.buscarUsuarioPorUsernameRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/UsuarioWS/listarUsuarioPorParametrosRequest", ReplyAction="http://services.buildup.pucp.edu.pe/UsuarioWS/listarUsuarioPorParametrosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.UsuarioWS.listarUsuarioPorParametrosResponse listarUsuarioPorParametros(BuildUp.UsuarioWS.listarUsuarioPorParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/UsuarioWS/listarUsuarioPorParametrosRequest", ReplyAction="http://services.buildup.pucp.edu.pe/UsuarioWS/listarUsuarioPorParametrosResponse")]
        System.Threading.Tasks.Task<BuildUp.UsuarioWS.listarUsuarioPorParametrosResponse> listarUsuarioPorParametrosAsync(BuildUp.UsuarioWS.listarUsuarioPorParametrosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class usuario : persona {
        
        private string passwordField;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidosField;
        
        private string correoField;
        
        private System.DateTime fechaFinContratoField;
        
        private bool fechaFinContratoFieldSpecified;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonaField;
        
        private string nombresField;
        
        private string rolField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFinContrato {
            get {
                return this.fechaFinContratoField;
            }
            set {
                this.fechaFinContratoField = value;
                this.RaisePropertyChanged("fechaFinContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinContratoSpecified {
            get {
                return this.fechaFinContratoFieldSpecified;
            }
            set {
                this.fechaFinContratoFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinContratoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuario", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class autenticarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.UsuarioWS.usuario usuario;
        
        public autenticarUsuarioRequest() {
        }
        
        public autenticarUsuarioRequest(BuildUp.UsuarioWS.usuario usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="autenticarUsuarioResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class autenticarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public autenticarUsuarioResponse() {
        }
        
        public autenticarUsuarioResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarUsuarioPorUsername", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarUsuarioPorUsernameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        public buscarUsuarioPorUsernameRequest() {
        }
        
        public buscarUsuarioPorUsernameRequest(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="buscarUsuarioPorUsernameResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class buscarUsuarioPorUsernameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.UsuarioWS.usuario @return;
        
        public buscarUsuarioPorUsernameResponse() {
        }
        
        public buscarUsuarioPorUsernameResponse(BuildUp.UsuarioWS.usuario @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuarioPorParametros", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuarioPorParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string username;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cargo;
        
        public listarUsuarioPorParametrosRequest() {
        }
        
        public listarUsuarioPorParametrosRequest(string username, string nombres, string apellidos, string cargo) {
            this.username = username;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.cargo = cargo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUsuarioPorParametrosResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarUsuarioPorParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.UsuarioWS.persona[] @return;
        
        public listarUsuarioPorParametrosResponse() {
        }
        
        public listarUsuarioPorParametrosResponse(BuildUp.UsuarioWS.persona[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsuarioWSChannel : BuildUp.UsuarioWS.UsuarioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioWSClient : System.ServiceModel.ClientBase<BuildUp.UsuarioWS.UsuarioWS>, BuildUp.UsuarioWS.UsuarioWS {
        
        public UsuarioWSClient() {
        }
        
        public UsuarioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsuarioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.UsuarioWS.autenticarUsuarioResponse BuildUp.UsuarioWS.UsuarioWS.autenticarUsuario(BuildUp.UsuarioWS.autenticarUsuarioRequest request) {
            return base.Channel.autenticarUsuario(request);
        }
        
        public int autenticarUsuario(BuildUp.UsuarioWS.usuario usuario) {
            BuildUp.UsuarioWS.autenticarUsuarioRequest inValue = new BuildUp.UsuarioWS.autenticarUsuarioRequest();
            inValue.usuario = usuario;
            BuildUp.UsuarioWS.autenticarUsuarioResponse retVal = ((BuildUp.UsuarioWS.UsuarioWS)(this)).autenticarUsuario(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.UsuarioWS.autenticarUsuarioResponse> BuildUp.UsuarioWS.UsuarioWS.autenticarUsuarioAsync(BuildUp.UsuarioWS.autenticarUsuarioRequest request) {
            return base.Channel.autenticarUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.UsuarioWS.autenticarUsuarioResponse> autenticarUsuarioAsync(BuildUp.UsuarioWS.usuario usuario) {
            BuildUp.UsuarioWS.autenticarUsuarioRequest inValue = new BuildUp.UsuarioWS.autenticarUsuarioRequest();
            inValue.usuario = usuario;
            return ((BuildUp.UsuarioWS.UsuarioWS)(this)).autenticarUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.UsuarioWS.buscarUsuarioPorUsernameResponse BuildUp.UsuarioWS.UsuarioWS.buscarUsuarioPorUsername(BuildUp.UsuarioWS.buscarUsuarioPorUsernameRequest request) {
            return base.Channel.buscarUsuarioPorUsername(request);
        }
        
        public BuildUp.UsuarioWS.usuario buscarUsuarioPorUsername(string username) {
            BuildUp.UsuarioWS.buscarUsuarioPorUsernameRequest inValue = new BuildUp.UsuarioWS.buscarUsuarioPorUsernameRequest();
            inValue.username = username;
            BuildUp.UsuarioWS.buscarUsuarioPorUsernameResponse retVal = ((BuildUp.UsuarioWS.UsuarioWS)(this)).buscarUsuarioPorUsername(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.UsuarioWS.buscarUsuarioPorUsernameResponse> BuildUp.UsuarioWS.UsuarioWS.buscarUsuarioPorUsernameAsync(BuildUp.UsuarioWS.buscarUsuarioPorUsernameRequest request) {
            return base.Channel.buscarUsuarioPorUsernameAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.UsuarioWS.buscarUsuarioPorUsernameResponse> buscarUsuarioPorUsernameAsync(string username) {
            BuildUp.UsuarioWS.buscarUsuarioPorUsernameRequest inValue = new BuildUp.UsuarioWS.buscarUsuarioPorUsernameRequest();
            inValue.username = username;
            return ((BuildUp.UsuarioWS.UsuarioWS)(this)).buscarUsuarioPorUsernameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.UsuarioWS.listarUsuarioPorParametrosResponse BuildUp.UsuarioWS.UsuarioWS.listarUsuarioPorParametros(BuildUp.UsuarioWS.listarUsuarioPorParametrosRequest request) {
            return base.Channel.listarUsuarioPorParametros(request);
        }
        
        public BuildUp.UsuarioWS.persona[] listarUsuarioPorParametros(string username, string nombres, string apellidos, string cargo) {
            BuildUp.UsuarioWS.listarUsuarioPorParametrosRequest inValue = new BuildUp.UsuarioWS.listarUsuarioPorParametrosRequest();
            inValue.username = username;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.cargo = cargo;
            BuildUp.UsuarioWS.listarUsuarioPorParametrosResponse retVal = ((BuildUp.UsuarioWS.UsuarioWS)(this)).listarUsuarioPorParametros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.UsuarioWS.listarUsuarioPorParametrosResponse> BuildUp.UsuarioWS.UsuarioWS.listarUsuarioPorParametrosAsync(BuildUp.UsuarioWS.listarUsuarioPorParametrosRequest request) {
            return base.Channel.listarUsuarioPorParametrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.UsuarioWS.listarUsuarioPorParametrosResponse> listarUsuarioPorParametrosAsync(string username, string nombres, string apellidos, string cargo) {
            BuildUp.UsuarioWS.listarUsuarioPorParametrosRequest inValue = new BuildUp.UsuarioWS.listarUsuarioPorParametrosRequest();
            inValue.username = username;
            inValue.nombres = nombres;
            inValue.apellidos = apellidos;
            inValue.cargo = cargo;
            return ((BuildUp.UsuarioWS.UsuarioWS)(this)).listarUsuarioPorParametrosAsync(inValue);
        }
    }
}
