//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.IngenieroWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="IngenieroWS.IngenieroWS")]
    public interface IngenieroWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/eliminarIngenieroRequest", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/eliminarIngenieroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.IngenieroWS.eliminarIngenieroResponse eliminarIngeniero(BuildUp.IngenieroWS.eliminarIngenieroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/eliminarIngenieroRequest", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/eliminarIngenieroResponse")]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.eliminarIngenieroResponse> eliminarIngenieroAsync(BuildUp.IngenieroWS.eliminarIngenieroRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/insertarIngenieroRequest", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/insertarIngenieroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.IngenieroWS.insertarIngenieroResponse insertarIngeniero(BuildUp.IngenieroWS.insertarIngenieroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/insertarIngenieroRequest", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/insertarIngenieroResponse")]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.insertarIngenieroResponse> insertarIngenieroAsync(BuildUp.IngenieroWS.insertarIngenieroRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/listarIngenieroRequest", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/listarIngenieroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.IngenieroWS.listarIngenieroResponse listarIngeniero(BuildUp.IngenieroWS.listarIngenieroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/listarIngenieroRequest", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/listarIngenieroResponse")]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.listarIngenieroResponse> listarIngenieroAsync(BuildUp.IngenieroWS.listarIngenieroRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/actualizarEstadoIngenieroRequest", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/actualizarEstadoIngenieroResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.IngenieroWS.actualizarEstadoIngenieroResponse actualizarEstadoIngeniero(BuildUp.IngenieroWS.actualizarEstadoIngenieroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/actualizarEstadoIngenieroRequest", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/actualizarEstadoIngenieroResponse" +
            "")]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.actualizarEstadoIngenieroResponse> actualizarEstadoIngenieroAsync(BuildUp.IngenieroWS.actualizarEstadoIngenieroRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/modificarIngenieroRequest", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/modificarIngenieroResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.IngenieroWS.modificarIngenieroResponse modificarIngeniero(BuildUp.IngenieroWS.modificarIngenieroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/modificarIngenieroRequest", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/modificarIngenieroResponse")]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.modificarIngenieroResponse> modificarIngenieroAsync(BuildUp.IngenieroWS.modificarIngenieroRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/obtenerEspecialidadIngenieroReque" +
            "st", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/obtenerEspecialidadIngenieroRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.IngenieroWS.obtenerEspecialidadIngenieroResponse obtenerEspecialidadIngeniero(BuildUp.IngenieroWS.obtenerEspecialidadIngenieroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/IngenieroWS/obtenerEspecialidadIngenieroReque" +
            "st", ReplyAction="http://services.buildup.pucp.edu.pe/IngenieroWS/obtenerEspecialidadIngenieroRespo" +
            "nse")]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.obtenerEspecialidadIngenieroResponse> obtenerEspecialidadIngenieroAsync(BuildUp.IngenieroWS.obtenerEspecialidadIngenieroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarIngeniero", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarIngenieroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idIngeniero;
        
        public eliminarIngenieroRequest() {
        }
        
        public eliminarIngenieroRequest(int idIngeniero) {
            this.idIngeniero = idIngeniero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarIngenieroResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarIngenieroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarIngenieroResponse() {
        }
        
        public eliminarIngenieroResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class ingeniero : persona {
        
        private string especialidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string especialidad {
            get {
                return this.especialidadField;
            }
            set {
                this.especialidadField = value;
                this.RaisePropertyChanged("especialidad");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ingeniero))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidosField;
        
        private string correoField;
        
        private System.DateTime fechaFinContratoField;
        
        private bool fechaFinContratoFieldSpecified;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonaField;
        
        private string nombresField;
        
        private string rolField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFinContrato {
            get {
                return this.fechaFinContratoField;
            }
            set {
                this.fechaFinContratoField = value;
                this.RaisePropertyChanged("fechaFinContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinContratoSpecified {
            get {
                return this.fechaFinContratoFieldSpecified;
            }
            set {
                this.fechaFinContratoFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinContratoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarIngeniero", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarIngenieroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.IngenieroWS.ingeniero ingeniero;
        
        public insertarIngenieroRequest() {
        }
        
        public insertarIngenieroRequest(BuildUp.IngenieroWS.ingeniero ingeniero) {
            this.ingeniero = ingeniero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarIngenieroResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarIngenieroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarIngenieroResponse() {
        }
        
        public insertarIngenieroResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngeniero", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngenieroRequest {
        
        public listarIngenieroRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngenieroResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarIngenieroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.IngenieroWS.ingeniero[] @return;
        
        public listarIngenieroResponse() {
        }
        
        public listarIngenieroResponse(BuildUp.IngenieroWS.ingeniero[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstadoIngeniero", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEstadoIngenieroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idIng;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool activo;
        
        public actualizarEstadoIngenieroRequest() {
        }
        
        public actualizarEstadoIngenieroRequest(int idIng, bool activo) {
            this.idIng = idIng;
            this.activo = activo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="actualizarEstadoIngenieroResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class actualizarEstadoIngenieroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public actualizarEstadoIngenieroResponse() {
        }
        
        public actualizarEstadoIngenieroResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarIngeniero", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarIngenieroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.IngenieroWS.ingeniero ingeniero;
        
        public modificarIngenieroRequest() {
        }
        
        public modificarIngenieroRequest(BuildUp.IngenieroWS.ingeniero ingeniero) {
            this.ingeniero = ingeniero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarIngenieroResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarIngenieroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarIngenieroResponse() {
        }
        
        public modificarIngenieroResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEspecialidadIngeniero", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEspecialidadIngenieroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idIngeniero;
        
        public obtenerEspecialidadIngenieroRequest() {
        }
        
        public obtenerEspecialidadIngenieroRequest(int idIngeniero) {
            this.idIngeniero = idIngeniero;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerEspecialidadIngenieroResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerEspecialidadIngenieroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public obtenerEspecialidadIngenieroResponse() {
        }
        
        public obtenerEspecialidadIngenieroResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IngenieroWSChannel : BuildUp.IngenieroWS.IngenieroWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IngenieroWSClient : System.ServiceModel.ClientBase<BuildUp.IngenieroWS.IngenieroWS>, BuildUp.IngenieroWS.IngenieroWS {
        
        public IngenieroWSClient() {
        }
        
        public IngenieroWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IngenieroWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngenieroWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngenieroWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.IngenieroWS.eliminarIngenieroResponse BuildUp.IngenieroWS.IngenieroWS.eliminarIngeniero(BuildUp.IngenieroWS.eliminarIngenieroRequest request) {
            return base.Channel.eliminarIngeniero(request);
        }
        
        public int eliminarIngeniero(int idIngeniero) {
            BuildUp.IngenieroWS.eliminarIngenieroRequest inValue = new BuildUp.IngenieroWS.eliminarIngenieroRequest();
            inValue.idIngeniero = idIngeniero;
            BuildUp.IngenieroWS.eliminarIngenieroResponse retVal = ((BuildUp.IngenieroWS.IngenieroWS)(this)).eliminarIngeniero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.eliminarIngenieroResponse> BuildUp.IngenieroWS.IngenieroWS.eliminarIngenieroAsync(BuildUp.IngenieroWS.eliminarIngenieroRequest request) {
            return base.Channel.eliminarIngenieroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.IngenieroWS.eliminarIngenieroResponse> eliminarIngenieroAsync(int idIngeniero) {
            BuildUp.IngenieroWS.eliminarIngenieroRequest inValue = new BuildUp.IngenieroWS.eliminarIngenieroRequest();
            inValue.idIngeniero = idIngeniero;
            return ((BuildUp.IngenieroWS.IngenieroWS)(this)).eliminarIngenieroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.IngenieroWS.insertarIngenieroResponse BuildUp.IngenieroWS.IngenieroWS.insertarIngeniero(BuildUp.IngenieroWS.insertarIngenieroRequest request) {
            return base.Channel.insertarIngeniero(request);
        }
        
        public int insertarIngeniero(BuildUp.IngenieroWS.ingeniero ingeniero) {
            BuildUp.IngenieroWS.insertarIngenieroRequest inValue = new BuildUp.IngenieroWS.insertarIngenieroRequest();
            inValue.ingeniero = ingeniero;
            BuildUp.IngenieroWS.insertarIngenieroResponse retVal = ((BuildUp.IngenieroWS.IngenieroWS)(this)).insertarIngeniero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.insertarIngenieroResponse> BuildUp.IngenieroWS.IngenieroWS.insertarIngenieroAsync(BuildUp.IngenieroWS.insertarIngenieroRequest request) {
            return base.Channel.insertarIngenieroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.IngenieroWS.insertarIngenieroResponse> insertarIngenieroAsync(BuildUp.IngenieroWS.ingeniero ingeniero) {
            BuildUp.IngenieroWS.insertarIngenieroRequest inValue = new BuildUp.IngenieroWS.insertarIngenieroRequest();
            inValue.ingeniero = ingeniero;
            return ((BuildUp.IngenieroWS.IngenieroWS)(this)).insertarIngenieroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.IngenieroWS.listarIngenieroResponse BuildUp.IngenieroWS.IngenieroWS.listarIngeniero(BuildUp.IngenieroWS.listarIngenieroRequest request) {
            return base.Channel.listarIngeniero(request);
        }
        
        public BuildUp.IngenieroWS.ingeniero[] listarIngeniero() {
            BuildUp.IngenieroWS.listarIngenieroRequest inValue = new BuildUp.IngenieroWS.listarIngenieroRequest();
            BuildUp.IngenieroWS.listarIngenieroResponse retVal = ((BuildUp.IngenieroWS.IngenieroWS)(this)).listarIngeniero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.listarIngenieroResponse> BuildUp.IngenieroWS.IngenieroWS.listarIngenieroAsync(BuildUp.IngenieroWS.listarIngenieroRequest request) {
            return base.Channel.listarIngenieroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.IngenieroWS.listarIngenieroResponse> listarIngenieroAsync() {
            BuildUp.IngenieroWS.listarIngenieroRequest inValue = new BuildUp.IngenieroWS.listarIngenieroRequest();
            return ((BuildUp.IngenieroWS.IngenieroWS)(this)).listarIngenieroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.IngenieroWS.actualizarEstadoIngenieroResponse BuildUp.IngenieroWS.IngenieroWS.actualizarEstadoIngeniero(BuildUp.IngenieroWS.actualizarEstadoIngenieroRequest request) {
            return base.Channel.actualizarEstadoIngeniero(request);
        }
        
        public int actualizarEstadoIngeniero(int idIng, bool activo) {
            BuildUp.IngenieroWS.actualizarEstadoIngenieroRequest inValue = new BuildUp.IngenieroWS.actualizarEstadoIngenieroRequest();
            inValue.idIng = idIng;
            inValue.activo = activo;
            BuildUp.IngenieroWS.actualizarEstadoIngenieroResponse retVal = ((BuildUp.IngenieroWS.IngenieroWS)(this)).actualizarEstadoIngeniero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.actualizarEstadoIngenieroResponse> BuildUp.IngenieroWS.IngenieroWS.actualizarEstadoIngenieroAsync(BuildUp.IngenieroWS.actualizarEstadoIngenieroRequest request) {
            return base.Channel.actualizarEstadoIngenieroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.IngenieroWS.actualizarEstadoIngenieroResponse> actualizarEstadoIngenieroAsync(int idIng, bool activo) {
            BuildUp.IngenieroWS.actualizarEstadoIngenieroRequest inValue = new BuildUp.IngenieroWS.actualizarEstadoIngenieroRequest();
            inValue.idIng = idIng;
            inValue.activo = activo;
            return ((BuildUp.IngenieroWS.IngenieroWS)(this)).actualizarEstadoIngenieroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.IngenieroWS.modificarIngenieroResponse BuildUp.IngenieroWS.IngenieroWS.modificarIngeniero(BuildUp.IngenieroWS.modificarIngenieroRequest request) {
            return base.Channel.modificarIngeniero(request);
        }
        
        public int modificarIngeniero(BuildUp.IngenieroWS.ingeniero ingeniero) {
            BuildUp.IngenieroWS.modificarIngenieroRequest inValue = new BuildUp.IngenieroWS.modificarIngenieroRequest();
            inValue.ingeniero = ingeniero;
            BuildUp.IngenieroWS.modificarIngenieroResponse retVal = ((BuildUp.IngenieroWS.IngenieroWS)(this)).modificarIngeniero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.modificarIngenieroResponse> BuildUp.IngenieroWS.IngenieroWS.modificarIngenieroAsync(BuildUp.IngenieroWS.modificarIngenieroRequest request) {
            return base.Channel.modificarIngenieroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.IngenieroWS.modificarIngenieroResponse> modificarIngenieroAsync(BuildUp.IngenieroWS.ingeniero ingeniero) {
            BuildUp.IngenieroWS.modificarIngenieroRequest inValue = new BuildUp.IngenieroWS.modificarIngenieroRequest();
            inValue.ingeniero = ingeniero;
            return ((BuildUp.IngenieroWS.IngenieroWS)(this)).modificarIngenieroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.IngenieroWS.obtenerEspecialidadIngenieroResponse BuildUp.IngenieroWS.IngenieroWS.obtenerEspecialidadIngeniero(BuildUp.IngenieroWS.obtenerEspecialidadIngenieroRequest request) {
            return base.Channel.obtenerEspecialidadIngeniero(request);
        }
        
        public string obtenerEspecialidadIngeniero(int idIngeniero) {
            BuildUp.IngenieroWS.obtenerEspecialidadIngenieroRequest inValue = new BuildUp.IngenieroWS.obtenerEspecialidadIngenieroRequest();
            inValue.idIngeniero = idIngeniero;
            BuildUp.IngenieroWS.obtenerEspecialidadIngenieroResponse retVal = ((BuildUp.IngenieroWS.IngenieroWS)(this)).obtenerEspecialidadIngeniero(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.IngenieroWS.obtenerEspecialidadIngenieroResponse> BuildUp.IngenieroWS.IngenieroWS.obtenerEspecialidadIngenieroAsync(BuildUp.IngenieroWS.obtenerEspecialidadIngenieroRequest request) {
            return base.Channel.obtenerEspecialidadIngenieroAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.IngenieroWS.obtenerEspecialidadIngenieroResponse> obtenerEspecialidadIngenieroAsync(int idIngeniero) {
            BuildUp.IngenieroWS.obtenerEspecialidadIngenieroRequest inValue = new BuildUp.IngenieroWS.obtenerEspecialidadIngenieroRequest();
            inValue.idIngeniero = idIngeniero;
            return ((BuildUp.IngenieroWS.IngenieroWS)(this)).obtenerEspecialidadIngenieroAsync(inValue);
        }
    }
}
