//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildUp.MaquinariaWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.buildup.pucp.edu.pe/", ConfigurationName="MaquinariaWS.MaquinariaWS")]
    public interface MaquinariaWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/MaquinariaWS/listarConParametrosRequest", ReplyAction="http://services.buildup.pucp.edu.pe/MaquinariaWS/listarConParametrosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(persona))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        BuildUp.MaquinariaWS.listarConParametrosResponse listarConParametros(BuildUp.MaquinariaWS.listarConParametrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.buildup.pucp.edu.pe/MaquinariaWS/listarConParametrosRequest", ReplyAction="http://services.buildup.pucp.edu.pe/MaquinariaWS/listarConParametrosResponse")]
        System.Threading.Tasks.Task<BuildUp.MaquinariaWS.listarConParametrosResponse> listarConParametrosAsync(BuildUp.MaquinariaWS.listarConParametrosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class maquinaria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private System.DateTime garantiaFinField;
        
        private bool garantiaFinFieldSpecified;
        
        private int idMaquinariaField;
        
        private lineaProduccion lineaProduccionField;
        
        private string nombreField;
        
        private proveedor proveedorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime garantiaFin {
            get {
                return this.garantiaFinField;
            }
            set {
                this.garantiaFinField = value;
                this.RaisePropertyChanged("garantiaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool garantiaFinSpecified {
            get {
                return this.garantiaFinFieldSpecified;
            }
            set {
                this.garantiaFinFieldSpecified = value;
                this.RaisePropertyChanged("garantiaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idMaquinaria {
            get {
                return this.idMaquinariaField;
            }
            set {
                this.idMaquinariaField = value;
                this.RaisePropertyChanged("idMaquinaria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public proveedor proveedor {
            get {
                return this.proveedorField;
            }
            set {
                this.proveedorField = value;
                this.RaisePropertyChanged("proveedor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class lineaProduccion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idLineaProduccionField;
        
        private string nombreField;
        
        private operario[] operariosField;
        
        private supervisor[] supervisoresField;
        
        private tipoLadrillo tipoLadrilloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLineaProduccion {
            get {
                return this.idLineaProduccionField;
            }
            set {
                this.idLineaProduccionField = value;
                this.RaisePropertyChanged("idLineaProduccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("operarios", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public operario[] operarios {
            get {
                return this.operariosField;
            }
            set {
                this.operariosField = value;
                this.RaisePropertyChanged("operarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("supervisores", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public supervisor[] supervisores {
            get {
                return this.supervisoresField;
            }
            set {
                this.supervisoresField = value;
                this.RaisePropertyChanged("supervisores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public tipoLadrillo tipoLadrillo {
            get {
                return this.tipoLadrilloField;
            }
            set {
                this.tipoLadrilloField = value;
                this.RaisePropertyChanged("tipoLadrillo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class operario : persona {
        
        private lineaProduccion lineaProduccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(supervisor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(operario))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidosField;
        
        private string correoField;
        
        private System.DateTime fechaFinContratoField;
        
        private bool fechaFinContratoFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonaField;
        
        private string nombresField;
        
        private string rolField;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("apellidos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaFinContrato {
            get {
                return this.fechaFinContratoField;
            }
            set {
                this.fechaFinContratoField = value;
                this.RaisePropertyChanged("fechaFinContrato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinContratoSpecified {
            get {
                return this.fechaFinContratoFieldSpecified;
            }
            set {
                this.fechaFinContratoFieldSpecified = value;
                this.RaisePropertyChanged("fechaFinContratoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string rol {
            get {
                return this.rolField;
            }
            set {
                this.rolField = value;
                this.RaisePropertyChanged("rol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class proveedor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string correoField;
        
        private int idProveedorField;
        
        private string razonSocialField;
        
        private string representanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idProveedor {
            get {
                return this.idProveedorField;
            }
            set {
                this.idProveedorField = value;
                this.RaisePropertyChanged("idProveedor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string razonSocial {
            get {
                return this.razonSocialField;
            }
            set {
                this.razonSocialField = value;
                this.RaisePropertyChanged("razonSocial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string representante {
            get {
                return this.representanteField;
            }
            set {
                this.representanteField = value;
                this.RaisePropertyChanged("representante");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class tipoLadrillo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double alturaField;
        
        private double anchoField;
        
        private int idTipoLadrilloField;
        
        private double largoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public double altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
                this.RaisePropertyChanged("altura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
                this.RaisePropertyChanged("ancho");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTipoLadrillo {
            get {
                return this.idTipoLadrilloField;
            }
            set {
                this.idTipoLadrilloField = value;
                this.RaisePropertyChanged("idTipoLadrillo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double largo {
            get {
                return this.largoField;
            }
            set {
                this.largoField = value;
                this.RaisePropertyChanged("largo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.buildup.pucp.edu.pe/")]
    public partial class supervisor : persona {
        
        private lineaProduccion lineaProduccionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public lineaProduccion lineaProduccion {
            get {
                return this.lineaProduccionField;
            }
            set {
                this.lineaProduccionField = value;
                this.RaisePropertyChanged("lineaProduccion");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarConParametros", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarConParametrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreMaquinaria;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreLineaProduccion;
        
        public listarConParametrosRequest() {
        }
        
        public listarConParametrosRequest(string nombreMaquinaria, string nombreLineaProduccion) {
            this.nombreMaquinaria = nombreMaquinaria;
            this.nombreLineaProduccion = nombreLineaProduccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarConParametrosResponse", WrapperNamespace="http://services.buildup.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarConParametrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.buildup.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public BuildUp.MaquinariaWS.maquinaria[] @return;
        
        public listarConParametrosResponse() {
        }
        
        public listarConParametrosResponse(BuildUp.MaquinariaWS.maquinaria[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MaquinariaWSChannel : BuildUp.MaquinariaWS.MaquinariaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaquinariaWSClient : System.ServiceModel.ClientBase<BuildUp.MaquinariaWS.MaquinariaWS>, BuildUp.MaquinariaWS.MaquinariaWS {
        
        public MaquinariaWSClient() {
        }
        
        public MaquinariaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaquinariaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaquinariaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaquinariaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BuildUp.MaquinariaWS.listarConParametrosResponse BuildUp.MaquinariaWS.MaquinariaWS.listarConParametros(BuildUp.MaquinariaWS.listarConParametrosRequest request) {
            return base.Channel.listarConParametros(request);
        }
        
        public BuildUp.MaquinariaWS.maquinaria[] listarConParametros(string nombreMaquinaria, string nombreLineaProduccion) {
            BuildUp.MaquinariaWS.listarConParametrosRequest inValue = new BuildUp.MaquinariaWS.listarConParametrosRequest();
            inValue.nombreMaquinaria = nombreMaquinaria;
            inValue.nombreLineaProduccion = nombreLineaProduccion;
            BuildUp.MaquinariaWS.listarConParametrosResponse retVal = ((BuildUp.MaquinariaWS.MaquinariaWS)(this)).listarConParametros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BuildUp.MaquinariaWS.listarConParametrosResponse> BuildUp.MaquinariaWS.MaquinariaWS.listarConParametrosAsync(BuildUp.MaquinariaWS.listarConParametrosRequest request) {
            return base.Channel.listarConParametrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<BuildUp.MaquinariaWS.listarConParametrosResponse> listarConParametrosAsync(string nombreMaquinaria, string nombreLineaProduccion) {
            BuildUp.MaquinariaWS.listarConParametrosRequest inValue = new BuildUp.MaquinariaWS.listarConParametrosRequest();
            inValue.nombreMaquinaria = nombreMaquinaria;
            inValue.nombreLineaProduccion = nombreLineaProduccion;
            return ((BuildUp.MaquinariaWS.MaquinariaWS)(this)).listarConParametrosAsync(inValue);
        }
    }
}
